"""English copy for the browser edition. The Japanese source stays authoritative."""

import re

BODY = {
    # Shell (U1): top bar, rail, drawer
    'aria-label="元に戻す・やり直す"': 'aria-label="Undo and redo"',
    'aria-label="メニュー" title="メニュー">⋯': 'aria-label="Menu" title="Menu">⋯',
    '<div id="captionMenu" class="caption-main-menu" hidden aria-label="メニュー">': '<div id="captionMenu" class="caption-main-menu" hidden aria-label="Menu">',
    '<nav id="captionRail" class="caption-rail" aria-label="パネル">': '<nav id="captionRail" class="caption-rail" aria-label="Panels">',
    '<span class="caption-rail-label">字幕</span>': '<span class="caption-rail-label">Captions</span>',
    '<span class="caption-rail-label">文字</span>': '<span class="caption-rail-label">Text</span>',
    '<span class="caption-rail-label">エフェクト</span>': '<span class="caption-rail-label">Effects</span>',
    '<span class="caption-rail-label">トラック</span>': '<span class="caption-rail-label">Tracks</span>',
    '<span class="caption-rail-label">動画</span>': '<span class="caption-rail-label">Video</span>',
    '<h2 id="captionDrawerTitle">字幕</h2>': '<h2 id="captionDrawerTitle">Captions</h2>',
    'aria-label="パネルを閉じる" title="パネルを閉じる"': 'aria-label="Close panel" title="Close panel"',
    'title="字幕編集の流れを見る">使い方</button>': 'title="How caption editing works">How to use</button>',
    'title="縞模様の部分はトリムで削除され、書き出されません"': 'title="Striped parts are trimmed away and not exported"',
    # Caption tab
    '単語を押すと修正・強調できます。✂ で字幕を分けます。</p>': 'Press a word to fix or highlight it. ✂ splits the caption there.</p>',
    '<h3 id="captionTextHeading">文字</h3>': '<h3 id="captionTextHeading">Text</h3>',
    '<h3 id="captionTimingHeading">タイミング</h3>': '<h3 id="captionTimingHeading">Timing</h3>',
    'aria-label="字幕の単語"': 'aria-label="Caption words"',
    '単語の文字<input id="captionWordText"': 'Word text<input id="captionWordText"',
    '<span id="captionWordEmphasisLabel">強調</span>': '<span id="captionWordEmphasisLabel">Highlight</span>',
    'data-emphasis="auto" aria-pressed="true">自動</button>': 'data-emphasis="auto" aria-pressed="true">Auto</button>',
    'data-emphasis="on" aria-pressed="false">する</button>': 'data-emphasis="on" aria-pressed="false">On</button>',
    'data-emphasis="off" aria-pressed="false">しない</button>': 'data-emphasis="off" aria-pressed="false">Off</button>',
    '開始（秒）<span class="caption-time-input">': 'Start (s)<span class="caption-time-input">',
    '終了（秒）<span class="caption-time-input">': 'End (s)<span class="caption-time-input">',
    'aria-label="開始を0.1秒早く"': 'aria-label="Start 0.1 s earlier"', 'aria-label="開始を0.1秒遅く"': 'aria-label="Start 0.1 s later"',
    'aria-label="終了を0.1秒早く"': 'aria-label="End 0.1 s earlier"', 'aria-label="終了を0.1秒遅く"': 'aria-label="End 0.1 s later"',
    '>開始を再生位置に</button>': '>Start at playhead</button>', '>終了を再生位置に</button>': '>End at playhead</button>',
    '>⇤ 前の字幕と結合</button>': '>⇤ Merge with previous</button>', '>次の字幕と結合 ⇥</button>': '>Merge with next ⇥</button>',
    '<h3>トラック</h3>': '<h3>Track</h3>',
    '>この字幕をまるごと移動</button>': '>Move the whole caption</button>',
    '一部の単語だけ移すときは、単語を選んでから移動します。': 'To move only some words, pick them, then move.',
    'aria-label="移動する単語"': 'aria-label="Words to move"',
    '<h3>見た目と動き</h3>': '<h3>Look and motion</h3>',
    '>この字幕のエフェクトを変える</button>': '>Change this caption’s effects</button>',
    '>ランダムに決める</button><': '>Randomize</button><',
    '<span>動かさない<small>この字幕だけアニメーションなしで表示します。</small></span>': '<span>No motion<small>Show only this caption without animation.</small></span>',
    '<span>この字幕を固定する<small>スタイルの変更やランダムでも、区切りと見た目が変わらなくなります。</small></span>': '<span>Keep this caption as is<small>Style changes and Randomize no longer change its words or look.</small></span>',
    '<summary>詳細</summary>': '<summary>Details</summary>',
    '<dt>タイミング</dt>': '<dt>Timing</dt>',
    '<summary>スタイルの種類</summary>': '<summary>Style family</summary>',
    '<summary>文字の見た目</summary>': '<summary>Text look</summary>',
    '<summary>位置と分量</summary>': '<summary>Position and amount</summary>',
    '<summary>動き</summary>': '<summary>Motion</summary>',
    'aria-label="エフェクトの項目"': 'aria-label="Effect stages"',
    'class="ghost small">自動</button>': 'class="ghost small">Auto</button>',
    'aria-label="閉じる">✕</button>': 'aria-label="Close">✕</button>',
    'aria-label="左パネルのタブ"': 'aria-label="Left panel tabs"',
    'aria-controls="captionLeftPane_transcript">文字起こし<': 'aria-controls="captionLeftPane_transcript">Transcript<',
    'aria-controls="captionLeftPane_roles">文字スタイル<': 'aria-controls="captionLeftPane_roles">Word styles<',
    'aria-controls="captionStylePane_video">動画設定<': 'aria-controls="captionStylePane_video">Video settings<',
    'aria-label="スタイルのタブ"': 'aria-label="Style tabs"',
    'aria-controls="captionStylePane_style">スタイル<': 'aria-controls="captionStylePane_style">Style<',
    'aria-controls="captionStylePane_effects">エフェクト<': 'aria-controls="captionStylePane_effects">Effects<',
    'aria-controls="captionStylePane_tracks">字幕トラック<': 'aria-controls="captionStylePane_tracks">Caption tracks<',
    '<h2 id="captionExportTitle">書き出し</h2>': '<h2 id="captionExportTitle">Export</h2>', 'aria-label="書き出しの進み具合"': 'aria-label="Export progress"',
    '>書き出しを開始</button>': '>Start export</button>', '書き出しを開始': 'Start export', '書き出しを準備しています…': 'Preparing the export…', '書き出し中…': 'Exporting…', 'キャンセル': 'Cancel',
    '>閉じる</button><button id="captionExportPanel"': '>Close</button><button id="captionExportPanel"',
    '字幕付きの MP4 を書き出します。ブラウザ内だけで処理され、動画はどこにも送信されません。': 'Export an MP4 with the captions burned in. Everything is processed in your browser; the video is never uploaded.',
    '<label class="caption-export-quality">画質': '<label class="caption-export-quality">Quality',
    '標準 — 軽いファイル・SNS向け': 'Standard — smaller file, good for social media',
    '高画質 — おすすめ': 'High — recommended',
    '最高画質 — 大きいファイル・時間がかかります': 'Maximum — largest file, slowest export',
    '高画質は元の動画の細部や小さな文字がきれいに残ります。画質を上げるほどファイルが大きく、書き出しに時間がかかります。': 'High keeps fine detail and small text in your video clean. Higher quality means a larger file and a slower export.',
    '<dt>形式</dt><dd id="captionExportFormat">': '<dt>Format</dt><dd id="captionExportFormat">',
    '<dt>長さ</dt><dd id="captionExportDuration">': '<dt>Length</dt><dd id="captionExportDuration">',
    '<dt>字幕</dt><dd id="captionExportCaptions">': '<dt>Captions</dt><dd id="captionExportCaptions">',
    '登場エフェクト': 'Entrance effect',
    'スタイルに合わせる': 'Match style',
    '文字の装飾': 'Text treatment',

    '台本を貼り付け': 'Paste a script',
    '台本（1行 = 1つの字幕）': 'Script (one line = one caption)',
    '字幕にする': 'Make captions',
    '再生位置からルーラーで指定した範囲の終わり（なければ動画の終わり）まで、同じ長さで並べます。「同期」で話すタイミングに合わせてください。': 'Lines are spread evenly from the playhead to the end of the range marked on the ruler (or the end of the video). Use Sync to match them to the speech.',
    '字幕はテキストブロックになります。自動の区切り直しで分割されず、別のトラックなら話している字幕と同時に表示できます。': 'Captions become text blocks. Re-segmenting never splits them, and on another track they can show at the same time as spoken captions.',
    '追加先のトラック<select id="captionManualTrack"': 'Add to track<select id="captionManualTrack"',
    'ブロックの登場<select id="captionBlockEnter"': 'Block entrance<select id="captionBlockEnter"',
    'ブロックの表示中<select id="captionBlockHold"': 'Block while visible<select id="captionBlockHold"',
    'ブロックの退場<select id="captionBlockExit"': 'Block exit<select id="captionBlockExit"',

    '<p id="captionProfileNote" class="caption-profile-note">読みやすさを優先した標準スタイルです。</p>': '<p id="captionProfileNote" class="caption-profile-note">A standard style prioritizing readability.</p>',
    'プレビューの動きを減らす': 'Reduce preview motion',
    '<label class="file caption-open-project">開く': '<label class="file caption-open-project">Open',
    '<strong>元の動画を再リンクしてください</strong>': '<strong>Relink the original video</strong>',
    '<p>プロジェクトには動画本体を保存しません。同じ動画を選ぶと編集を再開できます。</p>': '<p>Video bytes are not stored in the project. Choose the same video to resume editing.</p>',
    '>動画を再リンク<input id="captionRelinkFile"': '>Relink video<input id="captionRelinkFile"',
    '<div class="caption-timeline-toolbar"><span>タイムライン</span>': '<div class="caption-timeline-toolbar"><span>Timeline</span>',
    'aria-label="再生" title="再生 / 一時停止（Space）"': 'aria-label="Play" title="Play / pause (Space)"',
    'title="選んだ字幕、または指定した範囲をループ（L）。ルーラーを Alt+ドラッグで範囲指定">ループ': 'title="Loop the selected caption or the marked range (L). Alt+drag on the ruler to mark a range">Loop',
    'title="再生速度">1×': 'title="Playback speed">1×',
    'title="ドラッグ中に再生位置や他の字幕の端へ吸着します（Alt を押しながらドラッグで一時的にオフ）">スナップ': 'title="Snap to the playhead and to other captions while dragging (hold Alt to turn off for one drag)">Snap',
    '<span>ドラッグ取消 / ループ解除 / 選択解除</span>': '<span>Cancel drag / stop loop / deselect</span>', '<span>選んだ字幕を 0.05 秒ずらす</span>': '<span>Nudge the selected caption 0.05 s</span>',
    '<kbd>Shift+ドラッグ（端）</kbd><span>単語の長さも合わせて調整</span>': '<kbd>Shift+drag (edge)</kbd><span>Fit the words to the new length</span>',
    '<h3 id="captionKeysTitle">再生とタイムラインのキー</h3>': '<h3 id="captionKeysTitle">Playback and timeline keys</h3>',
    '<kbd>I / O</kbd><span>選んだ字幕の開始 / 終了を再生ヘッドに</span>': '<kbd>I / O</kbd><span>Selected caption starts / ends at the playhead</span>',
    '<kbd>Enter</kbd><span>選んだ字幕の文字を編集</span>': '<kbd>Enter</kbd><span>Edit the text of the selected caption</span>',
    '<kbd>Ctrl+Z / Ctrl+Shift+Z</kbd><span>元に戻す / やり直す</span>': '<kbd>Ctrl+Z / Ctrl+Shift+Z</kbd><span>Undo / redo</span>',
    'aria-label="字幕ブロック（Tab で選び、Enter で編集）"': 'aria-label="Caption blocks (Tab to select, Enter to edit)"',
    '<span>再生 / 一時停止</span>': '<span>Play / pause</span>', '<span>ループ オン/オフ</span>': '<span>Loop on / off</span>',
    '<span>1フレーム戻る / 進む</span>': '<span>Back / forward one frame</span>', '<span>1秒戻る / 進む</span>': '<span>Back / forward 1 s</span>',
    '<span>前 / 次の字幕</span>': '<span>Previous / next caption</span>', '<span>先頭 / 末尾</span>': '<span>Start / end</span>',
    '<span>拡大 / 縮小 / 全体</span>': '<span>Zoom in / out / fit</span>',
    '<p class="terms-sub">ルーラーを Alt+ドラッグ（または上半分をドラッグ）すると、ループする範囲を指定できます。</p>': '<p class="terms-sub">Alt+drag on the ruler (or drag its upper half) to mark a range to loop.</p>',
    'aria-label="タイムラインを縮小"': 'aria-label="Zoom timeline out"',
    'aria-label="タイムラインを拡大"': 'aria-label="Zoom timeline in"',
    'id="captionTimelineFit" type="button" class="small">全体': 'id="captionTimelineFit" type="button" class="small">Fit',
    '字幕あたりの単語数<input id="captionDensity"': 'Words per caption<input id="captionDensity"',
    '文字揃え<select id="captionAlignment"': 'Text alignment<select id="captionAlignment"',
    'aria-label="字幕の位置ボックス（矢印キーで移動、Shift で大きく移動）"': 'aria-label="Caption placement box (arrow keys move, Shift moves further)"',
    'aria-label="字幕の位置ボックス"': 'aria-label="Caption placement box"',
    '<h2>字幕の位置ボックス</h2>': '<h2>Caption placement box</h2>',
    'aria-label="エフェクト"': 'aria-label="Effects"',
    '<h2>エフェクト</h2>': '<h2>Effects</h2>',
    '動画全体の標準を決めて、あとから一部だけ変えられます。何も選ばなければスタイルの標準エフェクトになり、ランダムにはなりません。': 'Set a standard for the whole video, then change single parts later. Anything you leave unset uses the style standard; nothing is random.',
    '変更する対象<select id="captionLookScope"': 'Applies to<select id="captionLookScope"',
    'レイアウト<select id="captionLookLayout"': 'Layout<select id="captionLookLayout"',
    '登場<select id="captionLookEnter"': 'Entrance<select id="captionLookEnter"',
    '表示中<select id="captionLookHold"': 'While visible<select id="captionLookHold"',
    '退場<select id="captionLookExit"': 'Exit<select id="captionLookExit"',
    '話している単語<select id="captionLookActive"': 'Spoken word<select id="captionLookActive"',
    '>ランダムに決める</button>': '>Randomize</button>',
    '>標準に戻す</button>': '>Reset to standard</button>',
    'aria-label="文字スタイル"': 'aria-label="Word styles"',
    '<h2>文字スタイル</h2>': '<h2>Word styles</h2>',
    'aria-label="字幕トラック"': 'aria-label="Caption tracks"',
    '<h2>字幕トラック</h2>': '<h2>Caption tracks</h2>',
    'トラックの追加・名前の変更・並べ替え・削除は、タイムラインの左のトラック名から行います。ここでは、トラックごとの見た目を決めます。': 'Add, rename, reorder and delete tracks from the track names on the left of the timeline. Here you set each track’s look.',
    'aria-label="トラック一覧"': 'aria-label="Track list"',
    '>このトラックをランダムに決める</button>': '>Randomize this track</button>',
    'トラックのスタイル<select id="captionTrackPreset"': 'Track style<select id="captionTrackPreset"',
    'トラックの装飾<select id="captionTrackTreatment"': 'Track text treatment<select id="captionTrackTreatment"',
    'トラックのアクセント色<span class="caption-role-pair">': 'Track accent color<span class="caption-role-pair">',
    '全体に合わせる': 'Match project',
    '移動先のトラック<select id="captionMoveTrack"': 'Move to track<select id="captionMoveTrack"',
    '>選んだ単語を移動</button>': '>Move checked words</button>',
    '並びと改行は「すべての文字」で決まります。話している単語と強調する単語は、位置を動かさずに見た目だけ変わります。': 'All text sets the layout and line breaks. The spoken word and highlighted words only change how they look, never where they sit.',
    '<summary>すべての文字</summary>': '<summary>All text</summary>',
    '<summary>話している単語</summary>': '<summary>Word being spoken</summary>',
    '<summary>強調する単語</summary>': '<summary>Highlighted words</summary>',
    '編集するトラック<select id="captionRoleTrack">': 'Track<select id="captionRoleTrack">',
    'aria-label="文字スタイルの見本（2語目が話している単語、最後の語が強調する単語）"': 'aria-label="Word style sample (the second word is being spoken, the last word is highlighted)"',
    '<span>フォント</span><select id="captionRoleBaseFont">': '<span>Font</span><select id="captionRoleBaseFont">',
    '<span>色</span><input id="captionRole': '<span>Color</span><input id="captionRole',
    '<span>大きさ</span><input id="captionRole': '<span>Size</span><input id="captionRole',
    '<span>2つ目のフォント</span>': '<span>Second font</span>',
    '<span>強調する量</span>': '<span>How many</span>',
    'title="自動に戻す" aria-label="フォントを自動に戻す"': 'title="Back to automatic" aria-label="Font back to automatic"',
    'title="自動に戻す" aria-label="色を自動に戻す"': 'title="Back to automatic" aria-label="Color back to automatic"',
    'title="自動に戻す" aria-label="大きさを自動に戻す"': 'title="Back to automatic" aria-label="Size back to automatic"',
    'title="自動に戻す" aria-label="強調する量を自動に戻す"': 'title="Back to automatic" aria-label="How many back to automatic"',
    'title="元に戻す" aria-label="色を戻す"': 'title="Remove" aria-label="Remove color"',
    'title="元に戻す" aria-label="大きさを戻す"': 'title="Remove" aria-label="Remove size change"',
    'title="使わない" aria-label="2つ目のフォントを使わない"': 'title="None" aria-label="No second font"',
    'エフェクトの設定で話している単語の色が指定されているため、ここで選んだ色は使われません。': 'A color set in the spoken-word effect settings (Effects) is used instead of this one.',
    '>エフェクトを開く</button>': '>Open Effects</button>',
    '>固定を外す</button>': '>Remove override</button>',
    '数字や「!」のある単語が自動で選ばれます。単語ごとの指定は字幕の編集（✎ 文字）で変えられます。': 'Numbers, “!” and similar words are picked automatically. Change single words with ✎ Text.',
    '色・2つ目のフォント・大きさのどれかを選ぶと、強調する単語が目立つようになります。': 'Pick a color, second font or size to make highlighted words stand out. Until then they look like the rest.',
    '>文字スタイルをすべて初期値に戻す</button>': '>Reset all word styles</button>',
    '>既定</button>': '>Default</button>',
    '対象<select id="captionBoxScope"><option value="track">トラック全体</option><option id="captionBoxScopeSegment" value="segment">選択中の字幕のみ</option></select>': 'Applies to<select id="captionBoxScope"><option value="track">Whole track</option><option id="captionBoxScopeSegment" value="segment">Selected caption only</option></select>',
    '幅 (%)<input id="captionBoxWidth"': 'Width (%)<input id="captionBoxWidth"',
    '高さ (%)<input id="captionBoxHeight"': 'Height (%)<input id="captionBoxHeight"',
    '>位置を初期値に戻す</button>': '>Reset placement</button>',
    '<option value="left">左</option><option value="center">中央</option><option value="right">右</option>': '<option value="left">Left</option><option value="center">Center</option><option value="right">Right</option>',
    '文字方向<select id="captionWritingMode"': 'Text direction<select id="captionWritingMode"',
    '<option value="horizontal">横書き</option><option value="vertical">縦書き</option>': '<option value="horizontal">Horizontal</option><option value="vertical">Vertical</option>',
    '色<span class="caption-role-pair">': 'Color<span class="caption-role-pair">',
    '強調の強さ<input id="captionEmphasisStrength"': 'Emphasis strength<input id="captionEmphasisStrength"',
    '無題の字幕プロジェクト': 'Untitled caption project',
    '自動保存 ': 'Saved ', '自動保存できません': 'Autosave unavailable',
    'aria-label="字幕プロジェクト操作"': 'aria-label="Caption project actions"',
    '>新規</button>': '>New</button>',
    'id="captionUndo" type="button" disabled>元に戻す': 'id="captionUndo" type="button" disabled>Undo',
    'id="captionRedo" type="button" disabled>やり直す': 'id="captionRedo" type="button" disabled>Redo',
    '>全体をランダムに決める</button>': '>Randomize look</button>',
    'id="captionSave" type="button" disabled>保存': 'id="captionSave" type="button" disabled>Save',
    'title="文字スタイル・エフェクト・スタイルの設定をすべてファイルに保存します">スタイルを保存': 'title="Save every Word styles, Effects and Style setting to a file">Save Style',
    'title="保存したスタイルを、いまの字幕に適用します">スタイルを読込': 'title="Apply a saved style to the current captions">Load Style',
    'title="字幕付き MP4 を書き出す">書き出し': 'title="Export a captioned MP4">Export',
    'title="安全な演出の中から選べます"': 'title="Choose from the safe set of effects"',
    'title="演出の技法を自分で選べます"': 'title="Choose the effect techniques yourself"',
    'title="字幕編集の流れを見る" aria-label="使い方"': 'title="How caption editing works" aria-label="Help"',
    'id="captionTerms" type="button" class="ghost terms-open" title="出力物の権利とライセンス"': 'id="captionTerms" type="button" class="ghost terms-open" title="Rights and license of the output"',
    '<h2 id="captionRestoreTitle">前回の作業を復元しますか？</h2>': '<h2 id="captionRestoreTitle">Restore your last session?</h2>',
    '<p>このブラウザに自動保存されたプロジェクトがあります。</p>': '<p>A project was autosaved in this browser.</p>',
    '<dt>名前</dt><dd id="captionRestoreName">': '<dt>Name</dt><dd id="captionRestoreName">',
    '<dt>保存</dt><dd id="captionRestoreTime">': '<dt>Saved</dt><dd id="captionRestoreTime">',
    '<dt>字幕</dt><dd id="captionRestoreCount">': '<dt>Captions</dt><dd id="captionRestoreCount">',
    '動画ファイルは保存されません。復元後に元の動画を選び直してください。': 'The video file is not stored. After restoring, choose the original video again.',
    '<button value="discard" class="ghost">破棄して新規</button><button value="restore" class="primary" autofocus>復元</button>': '<button value="discard" class="ghost">Discard and start new</button><button value="restore" class="primary" autofocus>Restore</button>',
    '<h2 id="captionHelpTitle">字幕編集の流れ</h2>': '<h2 id="captionHelpTitle">How caption editing works</h2>',
    '<strong>動画を読み込む。</strong>動画は「動画設定」で、書き出す縦横比（9:16・4:5・1:1・16:9）、トリム、クロップを選びます。': '<strong>Import a video.</strong> In Video settings, choose the output shape (9:16, 4:5, 1:1 or 16:9), trim and crop.',
    '<strong>文字起こしを入れる。</strong>単語タイムスタンプ JSON、SRT、VTT を読み込むか、台本を貼り付けて「同期」で合わせます。': '<strong>Add a transcript.</strong> Import word-timestamp JSON, SRT or VTT, or paste a script and match it with Sync.',
    '<strong>スタイルを選ぶ。</strong>エフェクトは「エフェクト」で自分で選びます（ランダムに決めることもできます）。位置ボックスは動画の上でドラッグして決めます。': '<strong>Pick a style.</strong> Choose the effects yourself in Effects (or randomize them), and drag the placement box on the video.',
    '<strong>タイムラインで整える。</strong>字幕の境界をドラッグし、トラックを分けて重ねることもできます。': '<strong>Adjust on the timeline.</strong> Drag caption boundaries, or split captions onto separate tracks to overlap them.',
    '<strong>書き出す。</strong>字幕付き MP4 は、このブラウザの中で作られます。': '<strong>Export.</strong> The captioned MP4 is made inside this browser.',
    '<p class="terms-sub">かんたん：演出はおまかせ。詳細：演出の技法を自分で選べます。</p>': '<p class="terms-sub">Simple: effects are chosen for you. Advanced: choose the effect techniques yourself.</p>',
    'aria-label="文字起こしと字幕セグメント"': 'aria-label="Captions and transcript import"',
    '<h2>字幕</h2>': '<h2>Captions</h2>',
    'placeholder="字幕を検索" aria-label="字幕を検索"': 'placeholder="Search captions" aria-label="Search captions"',
    'title="警告のある字幕だけ表示">⚠ 警告のみ<': 'title="Show only captions with warnings">⚠ Warnings only<',
    '条件に合う字幕がありません。': 'No captions match.',
    'aria-label="左パネル"': 'aria-label="Left panel"',
    'aria-selected="true">文字起こし</button>': 'aria-selected="true">Transcript</button>',
    'aria-selected="false">動画設定</button>': 'aria-selected="false">Video settings</button>',
    'aria-label="動画設定"': 'aria-label="Video settings"',
    '<h2>動画設定</h2>': '<h2>Video settings</h2>',
    'aria-label="再生とタイムライン"': 'aria-label="Playback and timeline"',
    '>未読込</span>': '>Not imported</span>',
    '<strong>まず動画を読み込む</strong>': '<strong>Start by importing a video</strong>',
    '<p>ローカル動画はブラウザ内だけで扱われます。</p>': '<p>Your local video stays inside the browser.</p>',
    '>動画を選択<input id="captionVideoFile"': '>Choose video<input id="captionVideoFile"',
    '>文字起こしを読込<input id="captionTranscriptFile"': '>Import transcript<input id="captionTranscriptFile"',
    # AI transcription dialog (ADR 0011)
    '>AIで文字起こし</button>': '>Transcribe with AI</button>', '<h2 id="captionTranscribeTitle">AIで文字起こし</h2>': '<h2 id="captionTranscribeTitle">Transcribe with AI</h2>',
    '<p>動画の音声を Google の Gemini API に送り、単語ごとのタイミングが付いた字幕を作ります。今ある字幕は置き換えられます。</p>': "<p>Sends the audio of your video to Google's Gemini API and builds captions with per-word timing. Existing captions are replaced.</p>",
    '<strong>音声が Google に送信されます。</strong>映像は送信されません。無料枠の API キーでは、送信した内容が Google の製品改善に使われることがあります。': '<strong>The audio is sent to Google.</strong> The picture is not. With a free-tier API key, Google may use what you send to improve its products.',
    '<label class="caption-transcribe-field">Gemini API キー': '<label class="caption-transcribe-field">Gemini API key',
    '<p class="terms-sub">キーは <a href="https://aistudio.google.com/apikey"': '<p class="terms-sub">Create a key in <a href="https://aistudio.google.com/apikey"',
    '</a> で作れます。このブラウザにだけ保存され、プロジェクトファイルには含まれません。': '</a>. It is stored in this browser only and never in the project file.',
    '>保存したキーを消す</button>': '>Forget the saved key</button>',
    '<label class="caption-transcribe-field">話されている言語': '<label class="caption-transcribe-field">Spoken language',
    '<option value="">自動で判定</option>': '<option value="">Detect automatically</option>',
    '<option value="cmn-Hans-CN">中文（普通话）</option>': '<option value="cmn-Hans-CN">Chinese (Mandarin)</option>', '<option value="yue-Hant-HK">中文（粵語）</option>': '<option value="yue-Hant-HK">Chinese (Cantonese)</option>',
    '<option value="ja-JP">日本語</option>': '<option value="ja-JP">Japanese</option>', '<option value="ko-KR">한국어</option>': '<option value="ko-KR">Korean</option>',
    '<p class="terms-sub">7分までの動画に対応しています。歌や固有名詞は聞き間違えることがあるので、作成後に字幕を確認してください。</p>': '<p class="terms-sub">Works for videos up to 7 minutes. Songs and proper nouns can be misheard, so check the captions afterwards.</p>',
    '>文字起こしを開始</button>': '>Start transcription</button>',
    '「AIで文字起こし」で音声から自動で作るか、単語タイムスタンプ JSON、SRT、VTT を読み込むか、台本を貼り付けて「同期」で合わせます。': 'Create one from the audio with Transcribe with AI, import word-timestamp JSON, SRT or VTT, or paste a script and match it with Sync.',
    '>動画未選択</div>': '>No video selected</div>',
    'aria-label="字幕セグメント"': 'aria-label="Caption segments"',
    '① 動画を選ぶ → ② 字幕を追加（単語タイムスタンプ JSON・SRT・VTT を読み込む／台本を貼り付ける／タイムラインで入力）': '1 Choose a video → 2 Add captions (import word-timestamp JSON, SRT or VTT / paste a script / type on the timeline)',
    'aria-label="動画字幕プレビュー"': 'aria-label="Video caption preview"',
    'aria-label="動画と字幕のプレビュー"': 'aria-label="Video and caption preview"',
    '動画を選択してプレビューを開始': 'Choose a video to start previewing',
    'aria-label="動画の再生位置"': 'aria-label="Video position"',
    'aria-label="字幕タイムライン"': 'aria-label="Caption timeline"',
    'title="トラックを追加（最大3つ）">＋ トラック': 'title="Add a track (up to 3)">+ Track',
    '<kbd>Alt+↑ / ↓</kbd><span>選んだ字幕を上 / 下のトラックへ</span>': '<kbd>Alt+↑ / ↓</kbd><span>Move the selected caption to the track above / below</span>',
    '<kbd>N</kbd><span>再生ヘッドの位置に字幕を追加</span>': '<kbd>N</kbd><span>Add a caption at the playhead</span>',
    '<kbd>S</kbd><span>再生ヘッドで字幕を分割</span>': '<kbd>S</kbd><span>Split the caption at the playhead</span>',
    '<kbd>Delete</kbd><span>選んだ字幕を削除</span>': '<kbd>Delete</kbd><span>Delete the selected captions</span>',
    '<kbd>Shift+クリック</kbd><span>選択に追加 / 解除</span>': '<kbd>Shift+click</kbd><span>Add to / remove from the selection</span>',
    'トラックの空いている所をドラッグまたはダブルクリックすると字幕を追加できます。Shift+ドラッグで範囲選択、右クリックでメニュー（分割・結合・複製・削除）。': 'Drag or double-click an empty part of a track to add a caption. Shift+drag selects a range; right-click opens a menu (split, merge, duplicate, delete).',
    'aria-label="タイムラインの高さ" title="ドラッグで高さを変更、ダブルクリックで折りたたみ / 展開"': 'aria-label="Timeline height" title="Drag to resize, double-click to collapse / expand"',
    'aria-label="字幕スタイルとセグメント設定"': 'aria-label="Caption style and segment settings"',
    '<h2>スタイル</h2>': '<h2>Style</h2>',
    '登場エフェクト<select id="captionEffect"': 'Entrance<select id="captionEffect"',
    '文字の装飾<select id="captionTreatment"': 'Text finish<select id="captionTreatment"',
    'スタイルに合わせる': 'Match style',
    'スタイルファミリー<select id="captionStyle"': 'Style family<select id="captionStyle"',
    '強さ<input id="captionIntensity"': 'Intensity<input id="captionIntensity"',
    '動き<input id="captionMotion"': 'Motion<input id="captionMotion"',
    'アクセント色<input id="captionAccent"': 'Accent color<input id="captionAccent"',
    '<dt>開始</dt>': '<dt>Start</dt>', '<dt>終了</dt>': '<dt>End</dt>', '<dt>レイアウト</dt>': '<dt>Layout</dt>',
    '>準備完了</div>': '>Ready</div>',
    '<h1>動画に合わせて、読みやすく動く字幕を作る</h1>': '<h1>Create readable motion captions timed to your video</h1>',
    '<p>動画・文字起こし・スタイル・タイムラインをひとつの編集画面で扱うためのワークスペースです。</p>': '<p>A dedicated workspace for video, transcript, styling, and timeline editing.</p>',
    '<span class="product-build-status" role="status">エディターを構築中</span>': '<span class="product-build-status" role="status">Editor in development</span>',
    '文字PV系の部品を使う': 'Use typographic parts',
    'キネティックの部品を使う': 'Use kinetic parts',
    'ホラーの演出も使う': 'Include horror effects',
    '<small>線・数字・字組みだけで見せる、文字PVらしい部品（約50）</small>': '<small>About 50 parts that work with lines, numbers and type alone, in the spirit of lyric videos</small>',
    '<small>語ごとに動く・跳ねる・積み上がる、動き重視の部品（約50）</small>': '<small>About 50 motion-first parts: words move, bounce and stack one by one</small>',
    '<small>不気味な雰囲気の部品（約50）と配色セット3。オンにすると、おまかせの雰囲気に「ホラー」が加わります</small>': '<small>About 50 eerie parts and 3 styles. When on, Randomize adds a Horror mood</small>',
    '<small>「文」印の手法。オフにすると、おまかせやシャッフルでは選ばれません</small>': '<small>Techniques marked T. When off, Randomize and Shuffle skip them</small>',
    '<small>「キ」印の手法。オフにすると、おまかせやシャッフルでは選ばれません</small>': '<small>Techniques marked K. When off, Randomize and Shuffle skip them</small>',
    '<small>「ホ」印の手法とスタイル。おまかせでは雰囲気が「ホラー」のときだけ使います</small>': '<small>Techniques and styles marked H. Randomize uses them only in the Horror mood</small>',
    'title="スタイル・雰囲気・演出・配色をまるごとランダムに">おまかせ</button>': 'title="Randomize style, mood, effects and palette">Randomize</button>',
    'aria-controls="appMenu">メニュー</button>': 'aria-controls="appMenu">Menu</button>',
    'title="スマホ向けの画面（おまかせを上に固定、行はたたんで表示）">スマホ</button>': 'title="Phone layout (Randomize pinned at the top, lines folded)">Phone</button>',
    '<button class="exp-share primary" hidden>共有して保存</button>': '<button class="exp-share primary" hidden>Share / save</button>',
    '<label class="row center-dir" hidden>縦長のとき<select class="centerDirSel" aria-label="縦長の画面での分け方"><option value="tb">上下に分ける</option><option value="lr">左右に分ける</option></select></label>': '<label class="row center-dir" hidden>On tall frames<select class="centerDirSel" aria-label="Split on tall frames"><option value="tb">Top / bottom</option><option value="lr">Left / right</option></select></label>',
    '<span>統一感</span>': '<span>Unified look</span>',
    '<span>文字整列</span>': '<span>Typesetting</span>',
    'title="保存先のファイルを先に選び、そこへ直接書き込みます。長い曲・1080p 以上でブラウザのメモリが足りずに失敗するときに使ってください（Chrome / Edge）">大きな動画用（ファイルに直接保存）</button>': 'title="Pick the file first; the video is written straight into it. Use this when long songs or 1080p and above fail because the browser runs out of memory (Chrome / Edge)">For large videos (save straight to a file)</button>',
    'title="保存先のファイルを先に選び、そこへ直接書き込みます。長い曲・1080p 以上でブラウザのメモリが足りずに失敗するときに使ってください（Chrome / Edge）">MP4（大きな動画用・ファイルに直接保存）</button>': 'title="Pick the file first; the video is written straight into it. Use this when long songs or 1080p and above fail because the browser runs out of memory (Chrome / Edge)">MP4 (large videos, save straight to a file)</button>',
    '<span>中央を空ける（キャラクター用）<small>中央にキャラクターなどを重ねる前提で、文字と演出を横長の画面では左右、縦長の画面では上下に、行ごとに交互に置きます。背景と画面効果は全体のままです（プレビューには空ける範囲を点線で表示）</small></span>': '<span>Keep the centre free (for a character)<small>For a character or other footage in the middle: lyrics and their effects go to the left / right on wide frames and top / bottom on tall ones, alternating line by line. Backgrounds and screen effects still cover the whole frame (the preview outlines the free area with a dotted line)</small></span>',
    'title="歌詞と、行ごとのタイミング・指定・書き出す範囲を消します（「元に戻す」か Ctrl+Z で戻せます）">歌詞を消す</button>': 'title="Clear the lyrics with their line timings, per-line settings and export range (Undo or Ctrl+Z brings them back)">Clear lyrics</button>',
    'title="歌詞・曲・設定・履歴をすべて消して、最初の状態に戻します">初期化</button>': 'title="Clear lyrics, song, settings and history and start over">Reset</button>',
    '<h2 id="resetTitle">初期化</h2>': '<h2 id="resetTitle">Reset</h2>',
    '<p>次のものをすべて消して、最初の状態に戻します。<strong>元に戻すことはできません。</strong></p>': '<p>This clears everything below and starts over. <strong>It cannot be undone.</strong></p>',
    '<li>歌詞・曲名・アーティスト</li>': '<li>Lyrics, song title and artist</li>',
    '<li>読み込んだ曲（このブラウザに残していた分も）</li>': '<li>The loaded song (including the copy kept in this browser)</li>',
    '<li>タイミング・行ごとの指定・書き出す範囲</li>': '<li>Timing, per-line settings and export range</li>',
    '<li>スタイル・演出・配色・書体などの設定</li>': '<li>Style, motion, palette, fonts and other settings</li>',
    '<li>案の履歴（◀ ▶）と、歌詞・タイミングの「元に戻す」の履歴</li>': '<li>Variation history (◀ ▶) and the lyrics / timing undo history</li>',
    '<p class="terms-sub">表示モード（かんたん／詳細）・プレビューの音量・画面の言語はそのままです。保存したプロジェクトファイル（.json）も消えません。</p>': '<p class="terms-sub">Simple / Advanced mode, preview volume and the interface language stay as they are. Saved project files (.json) are not affected.</p>',
    '<button value="cancel" class="ghost">やめる</button><button value="reset" class="danger">初期化する</button>': '<button value="cancel" class="ghost">Cancel</button><button value="reset" class="danger">Reset</button>',
    '<li><code>[間奏 8]</code> … 8秒の間奏（歌詞は出さず、背景と装飾だけ）。秒数を省くと4秒、タップ同期やマーカーで長さを合わせられます</li>': '<li><code>[interlude 8]</code> … an 8-second instrumental part (no lyrics, background and decorations only). Without a number it lasts 4 seconds; tap sync or markers set its length</li>',
    '<button class="tour-skip ghost small">スキップ</button>': '<button class="tour-skip ghost small">Skip</button>',
    '<button class="tour-prev ghost small">戻る</button>': '<button class="tour-prev ghost small">Back</button>',
    '<button class="tour-next primary small">次へ</button>': '<button class="tour-next primary small">Next</button>',
    'title="かんたんモードの使い方を案内します" aria-label="使い方の案内"': 'title="A short tour of the Simple mode" aria-label="Tour"',
    '押し間違えたら <span class="kbd">Backspace</span> か「1つ戻る」。途中の行からやり直すときは、行一覧の ◎ を押します。': ' A wrong tap? Press <span class="kbd">Backspace</span> or “Undo tap”. To redo from a line in the middle, press ◎ in the line list.',
    '<button id="tapBack" class="ghost">1つ戻る</button>': '<button id="tapBack" class="ghost">Undo tap</button>',
    '行の区切り（上の目盛り）はドラッグで動かせます。<span class="kbd">Shift</span> で拍に吸着しない': 'Drag the line markers (top) to move line starts. Hold <span class="kbd">Shift</span> to ignore beats',
    'title="歌詞・タイミングの変更を元に戻す（Ctrl+Z）" disabled>元に戻す</button>': 'title="Undo lyric and timing changes (Ctrl+Z)" disabled>Undo</button>',
    'title="縮小" aria-label="タイムラインを縮小"': 'title="Zoom out" aria-label="Zoom the timeline out"',
    'title="拡大（タイムライン上でホイールでも）" aria-label="タイムラインを拡大"': 'title="Zoom in (or scroll on the timeline)" aria-label="Zoom the timeline in"',
    'title="全体を表示">全体</button>': 'title="Show the whole song">Fit</button>',
    'aria-label="タイムライン（クリックで移動・行の区切りはドラッグで調整）"': 'aria-label="Timeline (click to seek, drag line markers to adjust)"',
    '<span class="rng-lab">書き出す範囲</span>': '<span class="rng-lab">Export range</span>',
    'aria-label="書き出す範囲の最初の行"': 'aria-label="First line to export"',
    'aria-label="書き出す範囲の最後の行"': 'aria-label="Last line to export"',
    '<option value="en">English</option>': '<option value="en">English</option>',
    '後景（背景のグラフィックと歌詞の後ろの装飾）と前景（歌詞とその装飾・ゴースト）を、別々のフォルダ（back / front）に透過PNGで書き出します。画面全体の演出は両方にかかるので、前景を後景の上に重ねると通常の見た目になります': 'Transparent PNGs in two folders: back/ (background graphic and the decorations behind the lyrics) and front/ (lyrics, their decorations and ghosts). Screen effects are applied to both, so front over back matches the normal look.',
    '透過PNG 前景／後景（ZIP）': 'Transparent PNG layers (ZIP)',
    'title="クリックで消音／解除（プレビューだけ。書き出しの音量は変わりません）">音量</button>': 'title="Click to mute / unmute (preview only — exports keep the original level)">Vol</button>',
    'aria-label="プレビューの音量"': 'aria-label="Preview volume"',
    '歌詞の言語': 'Lyrics language', '<option value="auto">自動判定</option>': '<option value="auto">Auto-detect</option>',
    '<button id="btnAddFont">追加</button>': '<button id="btnAddFont">Add</button>',
    '曲名': 'Song title', '自動': 'Auto',
    '曲名（タイトルカード・HUDに表示）': 'Song title (shown on title cards and HUD)',
    'アーティスト': 'Artist', '表示モード': 'Editor mode',
    'おまかせボタン中心のシンプルな画面': 'A simple workspace focused on automatic creation',
    'すべての設定を表示': 'Show all settings',
    '保存したプロジェクト(.json)を開く': 'Open a saved project (.json)',
    'プロジェクトを .json で保存': 'Save project as .json',
    'After Effects パネル用の構成データを書き出す': 'Export project data for the After Effects panel',
    '出力物の権利とライセンス': 'Rights and licenses for your exports',
    '歌詞とタイミング': 'Lyrics and timing', 'スタイルと書き出し': 'Style and export',
    '歌詞（1行 = 1フレーズ）': 'Lyrics (one phrase per line)',
    '1行が1フレーズ。空行は少し間を空けます': 'One phrase per line. A blank line adds a short pause.',
    '夜明けの色を/覚えてる': 'I remember/the dawn',
    'でカットの切れ目を指定': 'marks a cut boundary',
    '… 強調（大きく・インパクト寄りの演出）': '… emphasis (larger, stronger effects)',
    '… フラッシュと揺れを入れる': '… adds a flash and shake',
    '… 注釈レイアウトの小さな文字': '… smaller text in annotation layouts',
    '… LRC のタイムスタンプをそのまま使用': '… uses an LRC timestamp',
    'で始まる行 … コメント（無視）': 'starts a comment (ignored)',
    '行末の': 'A trailing', '透明': 'transparent', '歌詞|ruby or note': 'lyrics|reading or note',
    '歌詞': 'Lyrics', '曲とタイミング': 'Audio and timing',
    '曲なし（読み込むと拍を検出してカットを合わせます）': 'No audio. Import a song to detect beats and align cuts.',
    'mp3 / wav / m4a など': 'MP3, WAV, M4A and more',
    '曲を読み込む': 'Import audio', '曲を再生しながら各行の頭でタップ': 'Tap at the start of each line while the song plays',
    'タップで同期': 'Tap to sync', '開始(秒)': 'Start (s)', '行の長さ': 'Line duration',
    '拍にスナップ': 'Snap to beat', '手動タイミングを消す': 'Clear manual timing',
    '曲に合わせて、各行が始まる瞬間に': 'Press', 'かボタンを押してください。': 'or the button as each line starts.',
    '次:': 'Next:', '終了する': 'Finish', '行とカット': 'Lines and cuts',
 'このカットだけ差し替え': 'Replace on this cut only',
 'このカットだけ構成を再抽選': 'Reshuffle this cut only',
 'このカットだけ手法をランダムに': 'Randomize this cut only',
 'このカットをシャッフル': 'Shuffled this cut',
 'このカットをおまかせ': 'Randomized this cut',
    '再生位置': 'Playback position', 'タイムライン（クリックで移動）': 'Timeline (click to seek)',
    '前の案に戻る': 'Previous variation', '次の案へ進む': 'Next variation',
    '設定はそのままで構成だけ再抽選（ロックした行は維持）': 'Shuffle the arrangement, keeping locked lines',
    'スタイル・雰囲気・演出・配色をまるごとランダムに（キー R）': 'Randomize style, mood, effects and colors (R)',
    '押すたびに、スタイル・雰囲気・動き・配色・構成がまるごと変わります。キーボードの': 'Each click changes the style, mood, motion, colors and arrangement. Press',
    'でも実行できます。': 'to do the same.',
    '最初の公開版のあとに追加した約350の演出・配色セット12・書体6も、おまかせやシャッフルの候補にします（オフのときは最初の公開版の演出だけ）': 'Include about 350 more effects, 12 styles and 6 fonts in random picks. Off uses the original set.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィック。オフにすると、おまかせやシャッフルで選ばれません': 'Include Japanese motifs such as lanterns, postcards, shoji, fans, family crests, waves and cherry blossoms in random picks.',
    '「追加」印の手法・スタイル・書体。オフのときは、おまかせやシャッフルで最初の公開版の演出だけを使います': 'Include techniques, styles and fonts marked New in automatic picks.',
    '「和」印の手法とスタイル。オフにすると、おまかせやシャッフルでは選ばれません（追加分の判定のあとに適用。行ごとに手動で指定した場合は使えます）': 'Include techniques and styles marked JP in automatic picks. Manual selections remain available.',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    'スタイルだけ別のものに': 'Change the style only', 'アクセント・ズレ色A/Bをランダムに': 'Randomize accent and offset colors',
    '動き・グリッチ・使う手法の雰囲気だけ': 'Change motion, glitch and technique mood',
    'レイアウトと動きの組み合わせだけ': 'Change the arrangement and motion only',
    '画面比': 'Aspect ratio', '解像度': 'Resolution', '画質': 'Quality',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'MP4 を書き出す': 'Export MP4', '書き出した動画の権利について': 'Rights to exported videos',
    'フォントの役割': 'Font roles', 'PCのフォント名（例: 游明朝）': 'Installed font name (e.g. Arial)',
    'フォントファイル（.ttf/.otf）': 'Font file (.ttf/.otf)',
    'アクセント・ズレ色': 'Accent and offset colors',
    '全シーンに適用。背景に合わせて明るさを自動調整します': 'Applies to every scene. Brightness adapts to the background.',
    '自分の色で上書き': 'Use custom colors', 'ランダムに配色': 'Randomize palette',
    '背景・文字色': 'Background and text colors', 'メインの背景と文字を自分の色にする': 'Use custom background and text colors',
    '動きを何枚/秒で描くか（出力fpsとは別）': 'Motion drawings per second (independent of export fps)',
    'フル（出力fpsのまま）': 'Full (export fps)', '2コマ打ち（12枚/秒）': 'On twos (12 drawings/s)',
    '3コマ打ち（8枚/秒）': 'On threes (8 drawings/s)',
    'スタイル次第': 'Auto (by style)', '常に表示': 'Always show', '表示しない': 'Hide',
    '同じシードなら同じ構成になります。行ごとの「再抽選」「ロック」は左の行リストから。': 'The same seed produces the same arrangement. Reroll or lock individual lines in the list on the left.',
    '手法を名前で絞り込み': 'Filter techniques by name',
    '画面に見えているプレビューは自動でループします。': 'Previews on screen loop automatically.',
    'グリーンバック／ブラックバックにすると、白い文字と演出だけを単色の背景の上に描きます（背景の模様・紙の質感・粒子・周辺減光は入りません）。プレビューにもそのまま反映されます。グリーンバックは動画編集ソフトのクロマキーで、ブラックバックは「スクリーン」合成や輝度キーで抜いて、別の映像の上に重ねられます。': 'Green screen and black background render white text and effects over a solid color, without background patterns, paper texture, particles or vignette. The preview shows the export. Use a chroma key for green or Screen blending / a luma key for black to composite over footage.',
    '曲を動画に含める': 'Include audio in video', '連番PNG（ZIP）': 'PNG sequence (ZIP)',
    '透過PNG（ZIP・背景なし）': 'Transparent PNG (ZIP)',
    '書き出した動画・画像の権利とライセンスについて': 'Rights and licenses for exported videos and images',
    '書き出しはこのブラウザの中で行われます（Chrome / Edge 推奨）。': 'Export runs in your browser (Chrome or Edge recommended).',
    'このツールで作った': 'You own the', '動画や画像（出力物）の権利は、作った人': 'videos and images you create',
    'に帰属します。': '.', '※ 使った歌詞や曲の権利は、それぞれの権利者に帰属します。': 'Lyrics and music remain the property of their respective rights holders.',
    'ツール本体は': 'The tool is released under the', 'ライセンス': 'license',
    'で公開しています。詳細なライセンスはこちら：': '. See the license at:',
    '入力した歌詞や曲は、このブラウザの中だけで処理され、サーバーには送信されません。': 'Your lyrics and audio are processed in this browser and are not sent to a server.',
    '使用しているオープンソース': 'Open source software', 'MP4 書き出し：': 'MP4 export: ',
    'フォント：': 'Fonts: ', '配布の各書体': 'typefaces', '閉じる': 'Close',
    'かんたん': 'Simple', '詳細': 'Advanced', '開く': 'Open', '保存': 'Save',
    'AE用に書き出し': 'Export for AE', '利用について': 'About / rights',
    '記法': 'Syntax', 'プレビュー': 'Preview', '再生': 'Play', 'ループ': 'Loop',
    '前の案': 'Previous', '次の案': 'Next', 'シャッフル': 'Shuffle', 'おまかせで作る': 'Create a variation',
    'おまかせ': 'Randomize', 'いまの案': 'Current variation', 'ここだけ変える': 'Change one thing',
    'スタイル': 'Style', '配色': 'Palette', '雰囲気': 'Mood', '構成': 'Arrangement',
    '書き出し': 'Export', '縦': 'portrait', '背景': 'Background',
    '追加': 'New', '和': 'JP', '演出': 'Effects', '手法': 'Techniques',
    'コマ打ち': 'Frame stepping', 'フラッシュ': 'Flash', 'シード': 'Seed', '新しいシード': 'New seed',
    '標準': 'Standard', '最高': 'Maximum', '高': 'High', '中止': 'Cancel',
    '行ループ': 'Line loop', 'カットループ': 'Cut loop',
    '全体を繰り返し': 'Loop the whole piece', 'この行を繰り返し': 'Loop this line',
    'このカットを繰り返し': 'Loop this cut', '繰り返しなし': 'No loop',







    'このカットだけ差し替え': 'Replace only this cut',
    'このカットだけ構成を再抽選': 'Re-roll the composition of only this cut',
    'このカットだけ手法をランダムに': 'Randomize the technique of only this cut',
    'このカットをシャッフル': 'Shuffle this cut',
    'このカットをおまかせ': 'Randomise this cut',
    'このカットをおまかせ': 'Randomize this cut',


}

UI = {
    "'文字PV系の部品：使う'": "'Typographic parts: on'",
    "'文字PV系の部品：使わない（おまかせ・シャッフルで選ばれません）'": "'Typographic parts: off (not picked by Randomize or Shuffle)'",
    "'キネティックの部品：使う'": "'Kinetic parts: on'",
    "'キネティックの部品：使わない（おまかせ・シャッフルで選ばれません）'": "'Kinetic parts: off (not picked by Randomize or Shuffle)'",
    "'ホラーの演出：使う（おまかせの雰囲気に「ホラー」が加わります）'": "'Horror effects: on (Randomize adds a Horror mood)'",
    "'ホラーの演出：使わない'": "'Horror effects: off'",
    "'（このセットがオフのため、おまかせでは選ばれません）'": "' (this set is off for automatic picks)'",
    "'（このセットがオフのため、自動では選ばれません）'": "' (this set is off for automatic picks)'",
    "{ name: 'ホラー', badge: 'ホ' }": "{ name: 'Horror', badge: 'H' }",
    "{ name: '文字PV系', badge: '文' }": "{ name: 'Typographic', badge: 'T' }",
    "{ name: 'キネティック', badge: 'キ' }": "{ name: 'Kinetic', badge: 'K' }",
    "'スマホの画面では 1080p で書き出します'": "'In the Phone layout the export is 1080p at most'",
    "`読み込んだ書体（${[...new Set(lost)].join('・')}）がこのブラウザにないため、書き出しを止めました。「フォント」から同じファイルを読み込み直すか、別の書体を選んでください`": "`The uploaded font (${[...new Set(lost)].join(', ')}) is not in this browser, so the export was stopped. Load the same file again under Fonts, or pick another font`",
    "`読み込んだ書体（${missing.join('・')}）がこのブラウザにありません。「フォント」から同じファイルを読み込み直してください（それまでは近い書体で表示します）`": "`The uploaded font (${missing.join(', ')}) is not in this browser. Load the same file again under Fonts (a similar font is used until then)`",
    "'縦長の画面：左右に分けます'": "'Tall frames: split left / right'",
    "'縦長の画面：上下に分けます'": "'Tall frames: split top / bottom'",
    "'（最初の方法では失敗したため、別のエンコーダーで書き出しました）'": "' (the first method failed, so another encoder was used)'",
    "'統一感：オン（パートごとにそろえ、キメ・モーフ・太さも使います）'": "'Unified look: on (parts match; hits, morphs and weight too)'",
    "'保存先を開けませんでした: '": "'Could not open the file: '",
    '`・「${fileName}」に保存しました`': '` · saved to “${fileName}”`',
    "'統一感：オフ'": "'Unified look: off'",
    "'文字整列：オン（字間・助詞・英字・0.2秒先・効果控えめ）'": "'Typesetting: on (spacing, particles, Latin, 0.2 s lead, fewer effects)'",
    "'文字整列：オフ'": "'Typesetting: off'",
    "`中央を空けました：文字と演出を${tall ? '上下' : '左右'}に置きます`": "`Centre kept free: lyrics and effects go ${tall ? 'top / bottom' : 'left / right'}`",
    "'中央を空けるのをやめました'": "'Centre no longer kept free'",
    "'歌詞を消しました（「元に戻す」か Ctrl+Z で戻せます）'": "'Lyrics cleared (Undo or Ctrl+Z brings them back)'",
    "'初期化しました'": "'Reset done'",
    "'歌詞・曲・設定・履歴をすべて消して、最初の状態に戻します。元に戻すことはできません。'": "'Clear lyrics, song, settings and history and start over? This cannot be undone.'",
    "(ln.interlude ? ' 間奏' : '')": "(ln.interlude ? ' inst.' : '')",
    "`〔間奏${ln.secs ? ' ' + ln.secs + '秒' : ''}〕`": "`[interlude${ln.secs ? ' ' + ln.secs + 's' : ''}]`",
    '\'<option value="">カット 自動</option>\'': '\'<option value="">Cuts: auto</option>\'',
    '`<option value="${n}">カット ${n}</option>`': '`<option value="${n}">Cuts: ${n}</option>`',
    'title="この行の歌詞を直す" aria-label="${i + 1}行目の歌詞を直す"': 'title="Edit this line’s lyrics" aria-label="Edit the lyrics of line ${i + 1}"',
    'aria-label="${i + 1}行目のカット数"': 'aria-label="Number of cuts in line ${i + 1}"',
    'title="この行からタップで同期し直す" aria-label="${i + 1}行目からタップ"': 'title="Tap sync again from this line" aria-label="Tap sync from line ${i + 1}"',
    'title="書き出す範囲にする（Shift+クリックで範囲を広げる）"': 'title="Set as the export range (Shift+click extends it)"',
    'aria-label="${i + 1}行目を書き出す範囲に"': 'aria-label="Export line ${i + 1}"',
    '`${ln.index + 1}行目の歌詞`': '`Lyrics of line ${ln.index + 1}`',
    "'記法（/ 区切り・*強調*・行末の ! ・| 注釈・[間奏 8]）もそのまま使えます。Enter で確定、Esc で取り消し'": "'Lyric syntax works here too (/ cut, *emphasis*, final !, | note, [interlude 8]). Enter to apply, Esc to cancel'",
    '`${ln.index + 1}行目の歌詞を直しました`': '`Line ${ln.index + 1} updated`',
    "'元に戻しました' : 'やり直しました'": "'Undone' : 'Redone'",
    "`書き出す範囲：${R2.from + 1}${R2.to > R2.from ? '〜' + (R2.to + 1) : ''}行目` : '書き出す範囲：全体'": "`Export range: line ${R2.from + 1}${R2.to > R2.from ? '–' + (R2.to + 1) : ''}` : 'Export range: whole song'",
    "'〔間奏〕' : ln.text).slice(0, 14)": "'[interlude]' : ln.text).slice(0, 14)",
    "opts(el, '全体')": "opts(el, 'Whole song')",
    '`${J.fmtTime(r.t0)} 〜 ${J.fmtTime(r.t1)}（${(r.t1 - r.t0).toFixed(1)}秒）` : `全体（${S.plan.duration.toFixed(1)}秒）`': '`${J.fmtTime(r.t0)} – ${J.fmtTime(r.t1)} (${(r.t1 - r.t0).toFixed(1)}s)` : `Whole song (${S.plan.duration.toFixed(1)}s)`',
    "'。このブラウザでは音声が Opus になり、iPhone・QuickTime などでは音が出ないことがあるため、音声を WAV でも保存しました' : '。このブラウザは音声を書き出せないため、音声を WAV で別に保存しました（動画編集ソフトで重ねてください）'": "'. This browser encodes audio as Opus, which iPhone, QuickTime and some players cannot play, so the audio was also saved as WAV' : '. This browser cannot encode audio, so the audio was saved separately as WAV (combine it in a video editor)'",
    "'。曲が読み込まれていないため音声なしです（「曲を読み込む」から読み込み直してください）'": "'. No song is loaded, so the video has no audio (load the song again with “Load song”)'",
    '`${from + 1}行目からタップで同期します（${J.fmtTime(t0)} から再生）`': '`Tap sync from line ${from + 1} (playing from ${J.fmtTime(t0)})`',
    "ln.interlude ? '〔間奏〕' : ln.text} ` : '—'": "ln.interlude ? '[interlude]' : ln.text} ` : '—'",
    "`${S.tap.i + 1}. ${ln.interlude ? '〔間奏〕' : ln.text}`": "`${S.tap.i + 1}. ${ln.interlude ? '[interlude]' : ln.text}`",
    "' · 前回の曲'": "' · last song'",
    "'・前回の曲'": "' · last song'",
    "title: '1. 歌詞を入れる', text: '1行が1フレーズになります。空行で少し間が空き、[間奏 8] と書くと8秒の間奏（背景と装飾だけ）になります。'": "title: '1. Enter lyrics', text: 'One line is one phrase. A blank line adds a short pause; [interlude 8] makes an 8-second instrumental part (background and decorations only).'",
    "title: '2. 曲を読み込む', text: 'mp3 などを読み込むと拍を検出して、カットの切り替わりを合わせます。曲がなくても作れます。「タップで同期」で行の頭を合わせることもできます。'": "title: '2. Load the song', text: 'Load an mp3 or similar file: JIZURA finds the beats and times the cuts to them. It also works without a song. “Tap to sync” lets you mark where each line starts.'",
    "title: '3. おまかせで作る', text: 'スタイル・雰囲気・動き・配色・構成をまるごと決めます。押すたびに別の案になり、「◀ 前の案」で戻れます。'": "title: '3. Create a variation', text: 'Style, mood, motion, palette and arrangement are chosen for you. Each press makes a new variation; “◀ Previous” goes back.'",
    "title: '4. 再生して確認する', text: '再生して見てみましょう。下のタイムラインでは、行の区切りをドラッグして動かせます（＋−で拡大）。'": "title: '4. Play it', text: 'Play it back. On the timeline below you can drag the line markers (+ and − zoom).'",
    "title: '5. 気になる行だけ直す', text: '行ごとに、歌詞を直す（✎）、カット数を決める、この行からタップし直す（◎）、この行だけ作り直す（サイコロ）ができます。'": "title: '5. Fix single lines', text: 'For each line you can edit the lyrics (✎), set the number of cuts, redo tap sync from that line (◎) or reroll just that line (dice).'",
    "title: '6. 書き出す', text: '画面比（縦長 9:16 など）と解像度を選んで MP4 を書き出します。「書き出す範囲」で選んだ行だけを書き出すこともできます。'": "title: '6. Export', text: 'Choose the aspect ratio (such as vertical 9:16) and resolution, then export MP4. “Export range” exports only the lines you pick.'",
    "'はじめる' : '次へ'": "'Start' : 'Next'",
    "'消音' : '音量'": "'Muted' : 'Vol'", "'音量 ' + Math.round": "'Volume ' + Math.round",
    '歌詞の言語：自動判定 → ': 'Lyrics language: auto-detect → ', '歌詞の言語：': 'Lyrics language: ',
    '${S.plan.cuts.length}カット': '${S.plan.cuts.length} cuts',
    '${i + 1}行目の開始秒': 'Line ${i + 1} start time (s)',
    'スタイル': 'Style', '雰囲気': 'Mood', '配色': 'Palette',
    '構成': 'Arrangement', '演出': 'Effects', '種': ' types',
    'のフォント': ' font',
    'で書き出します（': 'at (', '）。': '). ',
    '最初の公開版のあとに追加': 'Added after the original release', '和風の演出': 'Japanese motifs',
    'フォントを読み込み中…': 'Loading fonts…', '一時停止': 'Pause', '再生': 'Play',
    'この位置にカットはありません': 'No cut at this position',
    'スタイルの既定': 'Style default', '見出し書体': 'Display font',
    '見出し': 'Display', '明朝枠': 'Serif frame', '小さな文字': 'Small text',
    '背景の切替': 'Background changes', '動きの強さ': 'Motion strength',
    'カットの細かさ': 'Cut density', '装飾の量': 'Decoration amount',
    '文字の加工': 'Text treatments', '画面効果': 'Screen effects',
    'カット間のつなぎ': 'Transitions', 'レイアウト': 'Layout', '登場': 'Entrance',
    '保持': 'Hold', '退場': 'Exit', '装飾': 'Decoration', '加工': 'Treatment',
    'カメラ': 'Camera', 'つなぎ': 'Transition', '色ズレ': 'Color offset',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B', 'アクセント': 'Accent',
    '文字': 'Text', '補助': 'Secondary', '背景': 'Background',
    'グリッチ': 'Glitch', '質感': 'Texture',
    'この行の構成をロック': 'Lock this line', 'この行を再抽選': 'Reroll this line',
    'レイアウト指定': 'Choose layout', '開始（秒）': 'Start (s)',
    '・手動': ' · manual', '・自動': ' · automatic', '行目の開始秒': ' start time (s)',
    '行 / ': ' lines / ', 'カット': 'cuts', '行': 'line ',
    '自動': 'Auto', 'なし': 'None', 'カスタム': 'Custom',
    'ランダム': 'Random', '案目': 'variation', 'おまかせ：': 'Randomized: ',
    '配色：アクセント・ズレ色A/Bを変更': 'Palette: changed accent and offset colors',
    '構成：レイアウトと動きを再抽選': 'Arrangement: rerolled layout and motion',
    ' 種': ' types', '・': ' · ',
    'すべてON': 'All on', 'すべてOFF': 'All off', '反転': 'Invert',
    '（追加分がオフのため、おまかせでは選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、おまかせでは選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    '（追加分がオフのため、自動では選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、自動では選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    'グリーンバック': 'Green screen', 'ブラックバック': 'Black background',
    '白い文字と演出だけ': 'white text and effects only',
    '通常（スタイルの配色）': 'Style colors',
    'このブラウザは MP4 書き出しに対応していません（Chrome / Edge 推奨）': 'MP4 export is unavailable here (Chrome or Edge recommended)',
    'このブラウザでは ': 'This browser exports with ',
    '書き出し中はタブを開いたままにしてください。': 'Keep this tab open during export.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome / Edge の最新版で開くか、連番PNGを使ってください。': 'Video encoding (WebCodecs) is unavailable here. Try the latest Chrome or Edge, or export a PNG sequence.',
    '準備中…': 'Preparing…', '完成 ': 'Done: ', '秒': 's',
    '（保存はキャンセルされました）': ' (save canceled)', 'エラー: ': 'Error: ',
    '追加分の演出：使わない（最初の公開版の演出だけ）': 'New effects: off (original set only)',
    '追加分の演出：使う': 'New effects: on',
    '和風の演出：使わない（おまかせ・シャッフルで選ばれません）': 'Japanese motifs: off for random picks',
    '和風の演出：使う': 'Japanese motifs: on',
    'フォントを読み込めませんでした': 'Could not load the font',
    'プロジェクトを読み込めませんでした': 'Could not open the project',
    '解析中…': 'Analyzing audio…', '読み込めませんでした: ': 'Could not load: ',
    '約': 'about ', '（PC）': ' (installed)',
    '字面': 'JIZURA', '追加': 'New', '和': 'JP',
    'ループ': 'Loop',
    '行ループ': 'Line loop', 'カットループ': 'Cut loop',
    '全体を繰り返し': 'Loop the whole piece', 'この行を繰り返し': 'Loop this line',
    'このカットを繰り返し': 'Loop this cut', '繰り返しなし': 'No loop',
    # ロック（スライダー／手法の組／部品セット）
    "'おまかせでON／OFFを変えないようにロック'": "'Lock so Randomize keeps this group’s ON/OFF selection'",
    "'おまかせ／シャッフルで変えないようにロック'": "'Lock so Randomize / Shuffle leave this alone'",
    "'ロック中。クリックで解除'": "'Locked — click to unlock'",
    "'ロック：'": "'Locked: '",
    "'ロック解除：'": "'Unlocked: '",







    'この位置のカットは抽選できません': 'No cut at this position to re-roll',
    '`${i + 1}行目 カット${k + 1}のレイアウト`': '`Layout of cut ${k + 1} on line ${i + 1}`',
    'このカットだけ構成を再抽選': 'Re-roll the composition of only this cut',
    'このカットだけ手法をランダムに': 'Randomize the technique of only this cut',
    'このカットをシャッフル': 'Shuffle this cut',
    'このカットをおまかせ': 'Randomize this cut',
    'おまかせ': 'Randomize',
    'シャッフル': 'Shuffle',
}

CAPTION_UI = {
    # Shell (U1): drawer titles
    "captions: { title: '字幕'": "captions: { title: 'Captions'", "text: { title: '文字'": "text: { title: 'Text'", "effects: { title: 'エフェクト'": "effects: { title: 'Effects'",
    "tracks: { title: 'トラック'": "tracks: { title: 'Tracks'", "video: { title: '動画'": "video: { title: 'Video'",
    'スタイルを保存しました。': 'Style saved.', 'スタイルを読み込みました。元に戻すで戻せます。': 'Style loaded. Undo brings the old one back.',
    # Caption tab
    ": '選んだ単語を移動';": ": 'Move picked words';",
    "tags.push('テキストブロック')": "tags.push('Text block')", "tags.push('固定中')": "tags.push('Kept as is')",
    '`選んだ単語を移動（${picked}）`': '`Move picked words (${picked})`',
    '`登場: ${': '`Entrance: ${', "} · 表示中: ${": "} · While visible: ${", "} · 退場: ${": "} · Exit: ${",
    "'推定（SRT/VTT・手入力）'": "'Estimated (SRT/VTT or typed)'", "'字幕単位'": "'Caption level'",
    '`「${token.text}」の前で分割`': '`Split before “${token.text}”`', "' · 強調'": "' · highlighted'",
    "'文字は上の欄でまとめて書き換えます。単語を押すと強調を変えられます。'": "'Edit the text in the box above. Press a word to change its highlight.'",
    "'単語を押すと修正・強調できます。この字幕は固定中のため分割できません。'": "'Press a word to fix or highlight it. This caption is kept as is, so it cannot be split.'",
    "'単語を押すと修正・強調できます。✂ で字幕を分けます。'": "'Press a word to fix or highlight it. ✂ splits the caption there.'",
    "'推定タイミング' : '単語タイミング', on ? '強調されています' : '強調されていません'": "'estimated timing' : 'word timing', on ? 'highlighted' : 'not highlighted'",
    "'（強調の見た目は「文字スタイル」で設定します）'": "' (set how highlights look in Word styles)'",
    "'字幕を2つに分けました'": "'Split the caption in two'", "'字幕を結合しました'": "'Merged the captions'",
    # Tap sync (C4)
    'title="タップ同期: 選んだ字幕から最後まで（またはルーラーで指定した範囲）を、動画を再生しながら Space で合わせます">同期': 'title="Tap sync: play the video and press Space as each caption starts, from the selected caption to the end (or inside the range marked on the ruler)">Sync',
    "'同期を始める字幕を選ぶか、ルーラーで範囲を指定してください。'": "'Select the caption to start from, or mark a range on the ruler.'",
    "'動画を読み込んでください。'": "'Load a video first.'",
    "'同期できる字幕がありません。'": "'There are no captions to sync.'",
    "`次: 「${segmentText(session.byId.get(next.id))}」（${done + 1} / ${total}）`": "`Next: “${segmentText(session.byId.get(next.id))}” (${done + 1} / ${total})`",
    "!total ? '' : filtered ? `${shown.length} / ${total} 件` : `${total} 件`": "!total ? '' : filtered ? `${shown.length} / ${total}` : `${total}`",
    "`すべてタップしました（${total}件）。「確定」で反映します。`": "`All ${total} tapped. Press Confirm to apply.`",
    "`同期: 字幕が始まる瞬間に Space を押してください（${scope.items.length}件）。`": "`Sync: press Space the moment each caption starts (${scope.items.length}).`",
    "` 音声の字幕 ${spoken} 件は単語ごと動かします（長さは変わりません）。`": "` ${spoken} spoken caption(s) move with their words (length unchanged).`",
    "` 固定中の ${scope.skipped} 件は除きます。`": "` ${scope.skipped} kept-as-is caption(s) are skipped.`",
    "'タップ（Space）'": "'Tap (Space)'", "'字幕が始まる瞬間に押します。長く押すと、離した位置が終わりになります。'": "'Press as the caption starts. Hold to end it where you let go.'",
    "'反応遅れの補正'": "'Reaction offset'", "'タップの時刻からこの秒数だけ引きます'": "'Subtracted from every tap time'", "'反応遅れ'": "'Reaction'",
    "'確定（Enter）'": "'Confirm (Enter)'", "'破棄（Esc）'": "'Discard (Esc)'", "'タップ同期'": "'Tap sync'",
    "'同期を破棄しました。変更はありません。'": "'Sync discarded. Nothing changed.'", "'タップがなかったため、変更はありません。'": "'No taps, so nothing changed.'",
    "'タイミングは変わりませんでした。'": "'The timing did not change.'", "`${done}件の字幕のタイミングを同期しました`": "`Synced the timing of ${done} caption(s)`",
    # Tap sync for words (C5)
    '>単語を同期': '>Sync words', 'title="この字幕をループ再生し、各単語が始まる瞬間に Space を押して単語のタイミングを合わせます"': 'title="Loop this caption and press Space as each word starts to set the word timing"',
    "'単語を同期する字幕を選んでください。'": "'Select the caption whose words you want to sync.'",
    "'この字幕のタイミングは固定中のため、同期できません。'": "'The timing of this caption is kept as is, so it cannot be synced.'",
    "'同期できる単語がありません。'": "'There are no words to sync.'",
    "`単語の同期: 字幕がループします。各単語が始まる瞬間に Space を押してください（${tokens.length}語）。`": "`Word sync: the caption loops. Press Space the moment each word starts (${tokens.length}).`",
    "`${done}語のタイミングを同期しました`": "`Synced the timing of ${done} word(s)`",
    # Word styles panel
    "'自動（スタイルに合わせる）'": "'Auto (match style)'",
    "`${count.count} / ${count.total} 語`": "`${count.count} / ${count.total} words`",
    "'なし' : id === 'captionRoleEmphasisScale' ? '同じ' : '自動'": "'None' : id === 'captionRoleEmphasisScale' ? 'Same' : 'Auto'",
    '`動き方は「${effect}」です。エフェクトの「話している単語」で変えられます。`': '`It uses “${effect}”. Change it in Effects → Spoken word.`',
    '`動き方は「${effect}」です。詳細モードにすると、エフェクトで変えられます。`': '`It uses “${effect}”. Switch to Advanced to change it in Effects.`',
    '`このトラックでは話している単語の動きが「${lookLabel(\'active\', active.treatment)}」に固定され、エフェクトの設定より優先されています。`': '`This track fixes the spoken word to “${lookLabel(\'active\', active.treatment)}”, which overrides the Effects setting.`',
    'キャンセル': 'Cancel', '書き出し': 'Export',
    '書き出しをキャンセルしています…': 'Canceling export…',
    '書き出し環境を確認中': 'Checking export support', '字幕付き映像を書き出し中': 'Exporting captioned video',
    '元の音声を保持中': 'Preserving original audio', 'MP4を仕上げています': 'Finalizing MP4', '書き出し中': 'Exporting',
    '書き出しをキャンセルしました。': 'Export canceled.', '書き出しに失敗しました。': 'Export failed.',
    '安全性と読みやすさのため、この字幕は静止表示にフォールバックしました。文字数を減らすか、動きと強さを下げると再計画できます。': 'This caption fell back to a static treatment for safety and readability. Shorten it or reduce motion and intensity to replan.',
    'SRT/VTT の推定タイミングです。単語単位の強調を正確にするには、単語タイムスタンプ JSON を読み込んでください。': 'SRT/VTT timing is estimated. Import word-timestamp JSON for precise active-word emphasis.',
    '指定フォントを読み込めませんでした。ネットワークを確認するか、別のフォントを選んでください。': 'The selected font could not be loaded. Check the network or choose another font.',
    'フレーム・音声': ' frames · audio ', '保持': 'preserved', 'なし': 'none', '書き出しました（': 'Export complete (', '）。': ').',
    '位置ボックスが狭いため、文字がはみ出す可能性があります。': 'The placement box is narrow, so text may overflow.',
    '位置ボックスが無効です。': 'The placement box is invalid.',
    'スタイルに合わせる': 'Match style', '使わない': 'None',
    ': アプリに同梱されていないため、環境によって文字幅が変わる場合があります。': ': not bundled with the app, so text width may differ between machines.',
    '位置ボックスは画面内（0〜100%）に収めてください。': 'Keep the placement box inside the frame (0–100%).',
    '位置 X ': 'Position X ', '幅 ': 'Width ',
    '字幕が表示範囲からはみ出します。文字数・位置・サイズを調整してください。': 'Caption overflows its display area. Adjust density, position, or size.',
    '字幕の行数が多すぎます。字幕あたりの単語数を減らしてください。': 'Caption has too many lines. Reduce words per caption.',
    '背景とのコントラストを確認してください。アウトラインまたは背景板を推奨します。': 'Check contrast against the background. An outline or backplate is recommended.',
    '点滅を含む演出です。光過敏への配慮から別の演出を推奨します。': 'This effect contains flashing. Choose another effect for photosensitivity safety.',
    '字幕が推奨セーフエリアの外にあります。': 'Caption is outside the recommended safe area.',
    'アクセシビリティ警告': 'Accessibility warning',
    '動きと注目度が高いスタイルです。必要に応じて「プレビューの動きを減らす」を有効にしてください。': 'This style uses more motion and attention. Enable Reduce preview motion when appropriate.',
    '強調をはっきり見せる、中程度の動きのスタイルです。': 'A medium-motion style with clearly visible emphasis.',
    '読みやすさを優先した標準スタイルです。': 'A standard style prioritizing readability.',
    'プレビューの動きを減らしました。': 'Preview motion reduced.', '通常のプレビュー動作に戻しました。': 'Restored normal preview motion.',
    '動画を照合しています…': 'Verifying video…', '選択した動画は、このプロジェクトの元動画と一致しません。': 'The selected video does not match this project’s original video.',
    'プロジェクトを開いています…': 'Opening project…', 'Video Captions プロジェクトを選んでください。': 'Choose a Video Captions project.',
    '元動画': 'Original video', ' · 再リンクが必要': ' · relink required',
    'プロジェクトを開きました。元の動画を再リンクしてください。': 'Project opened. Relink the original video.', 'プロジェクトを開きました。': 'Project opened.',
    '無題の字幕プロジェクト': 'Untitled caption project',
    ' の終了境界': ' end boundary', '他の字幕と重なります。': 'Overlaps another caption.', '短すぎるか、動画の外です。': 'Too short, or outside the video.', '単語の範囲より狭くできません。': 'Cannot be narrower than its words.', 'この字幕はロック中です。': 'This caption is locked.', 'ドラッグを取り消しました。': 'Drag cancelled.', 'これ以上動かせません。': 'Cannot move further.', '字幕を選んでください。': 'Select a caption first.', '境界 ': 'Boundary ',
    '推定タイミング': 'Estimated timing', '単語タイミング': 'Word timing', '未読込': 'Not imported',
    '単語単位': 'Word level', '推定': 'Estimated', '単語': 'Word',
    'の前': ' before', ' 強調': ' Emphasize',
    '単語は空にできません。': 'A word cannot be empty.', 'この項目はロックされています。': 'This item is locked.',
    '開始と終了の時刻を確認してください。': 'Check the start and end times.', '分割位置を選び直してください。': 'Choose a different split point.',
    '隣り合う字幕だけ結合できます。': 'Only adjacent captions can be merged.', '変更を適用できませんでした。': 'The change could not be applied.',
    '変更を保存しました。': 'Change saved.', '字幕は含まれる単語と隣の字幕の範囲内に設定してください。': 'Keep the caption within its words and neighboring captions.',
    '動画を読み込んでいます…': 'Importing video…', '動画を読み込みました。文字起こしを追加できます。': 'Video imported. You can add a transcript.',
    '件の字幕を作成しました。': ' captions created.', '先に動画を読み込んでください。': 'Import a video first.', '今ある字幕はすべて置き換えられます。続けますか？': 'All existing captions will be replaced. Continue?',
    '音声を準備しています…': 'Preparing the audio…', '文字起こし中…（1分ほどかかることがあります）': 'Transcribing… (this can take about a minute)', '文字起こしをキャンセルしました。': 'Transcription cancelled.',
    '保存したキーを消しました。': 'Saved key removed.', "'文字起こしを開始'": "'Start transcription'", 'スタイルを更新しました。': 'Style updated.',
    '単語数を変えると、ロックされていない字幕の区切りが変わることがあります。続けますか？': 'Changing words per caption may alter unlocked caption boundaries. Continue?',
    '字幕の密度と区切りを更新しました。': 'Caption density and boundaries updated.', '新しいビジュアル案を作りました。': 'Created a new visual variation.',
    '動画未選択': 'No video selected', '新しいプロジェクトを作成しました。': 'Created a new project.', '選択した字幕をランダムに決めました。': 'Randomized the selected caption.',
    "hold: '保持'": "hold: 'Hold'",
    'レイアウト': 'Layout',
    '登場': 'Entrance',
    '退場': 'Exit',
    '装飾': 'Decor',
    '文字の加工': 'Text treatment',
    '背景': 'Background',
    'カメラ': 'Camera',
    '画面効果': 'Frame effect',
    'カット間のつなぎ': 'Transition',
    '追加分の演出も使う': 'Include new effects',
    '和風の演出も使う': 'Include Japanese motifs',
    '文字PV系の部品を使う': 'Use typographic parts',
    'キネティックの部品を使う': 'Use kinetic parts',
    'ホラーの演出も使う': 'Include horror effects',
    'すべてON': 'All on',
    'すべてOFF': 'All off',
    '反転': 'Invert',
    '手法を名前で絞り込み': 'Filter techniques by name',
    '他のトラックの字幕と位置が重なっています: ': 'Overlaps a caption on another track: ',
    '。位置ボックスを調整してください。': '. Adjust the placement box.',
    'トラックは最大3つまでです。': 'A project can have at most three tracks.',
    'メイントラックは削除できません。': 'The main track cannot be deleted.',
    'トラック名は1〜40文字で入力してください。': 'Track names need 1–40 characters.',
    'トラックのスタイルの値が正しくありません。': 'That track style value is not valid.',
    '移動する単語を選んでください。': 'Check the words to move.',
    'ロックされていない字幕がありません。': 'There are no unlocked captions.',
    '移動先のトラックで他の字幕と時間が重なります。先にその字幕を移動または短くしてください。': 'That would overlap another caption on the target track. Move or shorten it first.',
    '件の字幕': ' captions',
    '・メイン': ' · main',
    'トラックの位置ボックスが重なっています: ': 'Track placement boxes overlap: ',
    'トラックを追加しました。': 'Track added.',
    'ドラッグで重なり順を変更': 'Drag to change the stacking order', 'トラックのメニュー': 'Track menu', 'トラック名': 'Track name', '名前を変更': 'Rename', '上へ（下に重なる）': 'Up (drawn below)', '下へ（上に重なる）': 'Down (drawn on top)', 'エフェクトをランダムに決める': 'Randomize effects', 'トラックを削除': 'Delete track',
    'これより上のトラックはありません。': 'There is no track above.', 'これより下のトラックはありません。': 'There is no track below.', 'このトラックには字幕がありません。': 'This track has no captions.',
    'トラックを削除しました。': 'Track deleted.',
    '音声の波形を表示できません（長さが10分を超える動画では省略されます）。': 'The audio waveform is skipped for videos longer than 10 minutes.',
    '新しい字幕': 'New caption', '字幕の文字を更新しました。': 'Caption text updated.', '>字幕の文字<input': '>Caption text<input', '<dt>タイミングの精度</dt>': '<dt>Timing source</dt>', "'字幕の編集'": "'Edit caption'", '字幕を追加しました。文字を入力して Enter で確定します。': 'Caption added. Type its text and press Enter.',
    'ここには字幕を追加できません（同じトラックの字幕と重なります）。': 'A caption cannot be added here (it would overlap one on the same track).',
    '分割できるのは1つの字幕だけです。': 'Only one caption can be split at a time.', 
    '件の字幕を動かしました。': ' captions moved.', '件の字幕を選択しました。': ' captions selected.', '選択を解除しました。': 'Selection cleared.',
    '件の字幕を複製しました`': ' captions duplicated`', '件の字幕を削除しました`': ' captions deleted`',
    '再生ヘッドで分割': 'Split at playhead', '前の字幕と結合': 'Merge with previous', '次の字幕と結合': 'Merge with next', "'複製'": "'Duplicate'", "'削除'": "'Delete'", '複製（': 'Duplicate (', '削除（': 'Delete (', '件）': ' captions)',
    "'元に戻す'": "'Undo'", '選択中の字幕の操作': 'Actions for the selected caption', '警告を表示': 'Show warnings', '警告 ${': 'Warnings: ${', '✎ 文字': '✎ Text', '文字を編集': 'Edit the text',
    '✂ 分割': '✂ Split', '再生ヘッドで分割 (S)': 'Split at playhead (S)', '⇤ ここから': '⇤ Start here', '開始を再生ヘッドに合わせる (I)': 'Set the start to the playhead (I)',
    'ここまで ⇥': 'End here ⇥', '終了を再生ヘッドに合わせる (O)': 'Set the end to the playhead (O)', '単語が範囲外になるため、単語の時刻を新しい範囲に合わせました（推定）。': 'A word was in the way, so the words were fitted into the new range (estimated).', '✦ 見た目': '✦ Look', '見た目と動きを編集': 'Edit look and motion', 'その他の操作': 'More actions',
    '字幕の警告': 'Caption warnings', 'トラックへ移動しました: ': 'Moved to track: ', 'トラックへ移動: ': 'Move to track: ', "'動かさない: 解除'": "'Motion on'", "'動かさない'": "'No motion'",
    "'固定を解除'": "'Unlock'", "'このまま固定'": "'Keep as is'",
    'トラック「': 'Delete track "',
    '」を削除します。このトラックの字幕（': '". The track holds ',
    '件）と単語も削除されます。「元に戻す」で復元できます。続けますか？': ' captions; they and their words are deleted too. Undo restores them. Continue?',
    'トラックのエフェクトをランダムに決めました。': 'Randomized the track effects.',
    '全体のエフェクトをランダムに決めました。元に戻すで戻せます。': 'Randomized the effects for the whole video. Undo brings the old ones back.',
    'エフェクトをランダムに決めました。決めた内容は固定され、元に戻すで戻せます。': 'Randomized the effects. The result is now fixed and Undo brings the old ones back.',
    '選んだエフェクトが正しくありません。': 'That effect is not valid.',
    '全体（すべてのトラック）': 'Whole video (all tracks)', '全体（すべての字幕）': 'Whole video (all captions)', '選択中の字幕だけ': 'Selected caption only', '`トラック: ${': '`Track: ${',
    "text: 'トラックに合わせる'": "text: 'Match track'", "text: '標準'": "text: 'Standard'",
    "layout: 'レイアウト', enter: '登場', hold: '表示中', exit: '退場', active: '話している単語', treat: '文字の加工'": "layout: 'Layout', enter: 'Entrance', hold: 'While visible', exit: 'Exit', active: 'Spoken word', treat: 'Text treatment'",
    ': 選んだエフェクトはこの字幕では使えないため、安全な標準に置き換えました。': ': The effect you chose cannot be used on this caption, so the safe standard is used instead.',
    '文字が入りきらないため、サイズを ${item.from} から ${item.to} に下げました。文字数か位置ボックスを調整すると元のサイズに戻せます。': 'The text did not fit, so the size was reduced from ${item.from} to ${item.to}. Shorten the text or adjust the box to restore it.',
    '動きが多めの組み合わせです。読みにくい場合は、エフェクトを控えめにしてください。': 'This combination has a lot of motion. If it is hard to read, choose calmer effects.',
    '字幕を別のトラックへ移動しました。': 'Moved to the other track.',
    '自動（スタイルに合わせる）': 'Automatic (match style)',
    'この時間には同じトラックに別の字幕があります。別のトラックを選ぶか、空いている時間を指定してください。': 'Another caption on the same track uses this time. Choose another track or an empty time range.',
    '字幕の終了が動画の長さを超えています。': 'The caption ends after the video does.',
    'ブロックのアニメーションが正しくありません。': 'That block animation is not available.',
    'テキストブロックではありません。': 'This is not a text block.',
    'テキストブロック「': 'Delete text block "',
    '」を削除します。「元に戻す」で復元できます。続けますか？': '"? Undo restores it. Continue?',
    'テキストブロックを削除しました。': 'Text block deleted.',
    # effect settings (Advanced look panel)
    "'all.duration': '長さ（秒）'": "'all.duration': 'Length (s)'",
    "'all.strength': '動きの強さ'": "'all.strength': 'Motion strength'",
    "'color': '色'": "'color': 'Color'",
    "'colorA': '上の色'": "'colorA': 'Top color'",
    "'colorB': '下の色'": "'colorB': 'Bottom color'",
    "'splitColor.sp': '色の境目'": "'splitColor.sp': 'Split position'",
    "'k': '線の太さ'": "'k': 'Line width'",
    "'doubleOutline.a': '内側の縁の太さ'": "'doubleOutline.a': 'Inner edge width'",
    "'doubleOutline.b': '外側の縁の太さ'": "'doubleOutline.b': 'Outer edge width'",
    "'doubleOutline.color': '外側の縁の色'": "'doubleOutline.color': 'Outer edge color'",
    "'extrude.d': '奥行き'": "'extrude.d': 'Depth'",
    "'extrude.color': '側面の色'": "'extrude.color': 'Side color'",
    "'longShadow.L': '影の長さ'": "'longShadow.L': 'Shadow length'",
    "'longShadow.ang': '影の角度'": "'longShadow.ang': 'Shadow angle'",
    "'hardShadow.d': '影のずれ'": "'hardShadow.d': 'Shadow offset'",
    "'softShadow.b': '影のぼかし'": "'softShadow.b': 'Shadow blur'",
    "'softShadow.dy': '影の下へのずれ'": "'softShadow.dy': 'Shadow drop'",
    "'longShadow.color': '影の色'": "'longShadow.color': 'Shadow color'",
    "'hardShadow.color': '影の色'": "'hardShadow.color': 'Shadow color'",
    "'softShadow.color': '影の色'": "'softShadow.color': 'Shadow color'",
    "'glow.b': '光の広がり'": "'glow.b': 'Glow size'",
    "'glow.color': '光の色'": "'glow.color': 'Glow color'",
    "'outline.color': '線の色'": "'outline.color': 'Line color'",
    "'outlineFill.color': '縁の色'": "'outlineFill.color': 'Edge color'",
    "'captionOutlined.color': '縁の色'": "'captionOutlined.color': 'Edge color'",
    "'captionActiveScale.scale': '拡大'": "'captionActiveScale.scale': 'Scale'",
    "'captionActiveLift.lift': '持ち上げ'": "'captionActiveLift.lift': 'Lift'",
    "'captionActiveWeight.weight': '太さ（ウェイト）'": "'captionActiveWeight.weight': 'Weight'",
    '`${lookLabel(stage, effectId)} の設定`': '`${lookLabel(stage, effectId)} settings`',
    "'このエフェクトには調整できる設定がありません。'": "'This effect has no adjustable settings yet.'",
    "'自動に戻す'": "'Back to automatic'",
    "const unsetText = from != null ? inherit.text : '自動';": "const unsetText = from != null ? inherit.text : 'Auto';",
}

VIDEO_UI = {
    # Video settings (src/12a_video_edit_ui.js)
    "name: 'ショート・リール'": "name: 'Shorts · Reels'", "name: '縦長の投稿'": "name: 'Portrait post'", "name: '正方形'": "name: 'Square post'", "name: 'YouTube（横）'": "name: 'YouTube'",
    "name: '全体を表示'": "name: 'Fit'", "'動画全体が見え、余白は指定の色になります。'": "'The whole video shows; the empty space uses the bar color.'",
    "name: '画面を埋める'": "name: 'Fill'", "'画面いっぱいに拡大し、はみ出た端は切り取られます。'": "'The video is enlarged to fill the frame; edges that stick out are cut off.'",
    "name: 'ぼかし背景'": "name: 'Blurred background'", "'動画全体が見え、余白には同じ動画をぼかして敷きます。'": "'The whole video shows over a blurred copy of itself.'",
    "name: '全体'": "name: 'Full frame'", "name: '上下に分割'": "name: 'Stacked'", "name: '左右に分割'": "name: 'Side by side'", "name: 'ワイプ'": "name: 'Picture in picture'",
    '<h3 class="vs-title">出力の形</h3>': '<h3 class="vs-title">Output shape</h3>', 'aria-label="出力の形"': 'aria-label="Output shape"',
    '<h4 class="vs-subtitle">動画の形が出力と違うとき</h4>': '<h4 class="vs-subtitle">When the video has a different shape</h4>', 'aria-label="動画の収め方"': 'aria-label="How the video fills the frame"',
    '余白の色<input': 'Bar color<input', '<summary>トリム</summary>': '<summary>Trim</summary>',
    '明るい部分が書き出されます。端をドラッグして長さを変え、再生位置で分割して不要な区間を削除します。時間は元の動画の時間です。': 'The bright parts are exported. Drag an edge to change a section, split at the playhead and delete what you do not need. Times are in the original video.',
    'aria-label="残す区間"': 'aria-label="Kept sections"',
    '>✂ 再生位置で分割<': '>✂ Split at playhead<', '>区間の開始を再生位置に<': '>Section starts here<', '>区間の終了を再生位置に<': '>Section ends here<',
    '>選択した区間を削除<': '>Delete selected section<', '>削除した部分を戻す<': '>Restore removed part<', '>全体に戻す<': '>Restore full video<',
    '<summary>正確な時間（秒）</summary>': '<summary>Exact times (seconds)</summary>', '<summary>レイアウトと切り抜き</summary>': '<summary>Layout &amp; crop</summary>',
    '画面を分けて、元の動画の一部を並べます。各パネルは選んだ範囲で画面を埋めます。': 'Split the frame and show parts of the original video. Each panel fills its area with the chosen crop.',
    'aria-label="レイアウト"': 'aria-label="Layout"', 'aria-label="パネル"': 'aria-label="Panels"',
    '<figcaption>元の動画 · ドラッグで範囲を選ぶ</figcaption>': '<figcaption>Source · drag to choose the crop</figcaption>',
    'aria-label="切り抜く範囲。キーボードでは下の正確な値を使います"': 'aria-label="Crop area; with a keyboard, use the exact values below"',
    '<figcaption>出力 · ドラッグで移動</figcaption>': '<figcaption>Output · drag to move</figcaption>',
    'aria-label="パネルの配置。キーボードでは下の正確な値を使います"': 'aria-label="Panel placement; with a keyboard, use the exact values below"',
    '<summary>正確な値（%）</summary>': '<summary>Exact values (%)</summary>', '<summary>画像の重ね合わせ</summary>': '<summary>Image overlays</summary>',
    '透明部分のある PNG（フレーム・ロゴ・テンプレート）を重ねます。最大4枚。プロジェクトに保存され、テンプレートとして他のプロジェクトでも使えます。': 'Add a PNG with transparent areas (a frame, logo or template) on top of the video, up to 4. Overlays are saved with the project; save them as a template to reuse them in other projects.',
    '>PNG を追加<': '>Add PNG<', '>テンプレートを保存<': '>Save template<', '>テンプレートを読込<': '>Load template<',
    '<summary>テキストメモ</summary>': '<summary>Text notes</summary>',
    '字幕とは別の、シンプルな文字です。それぞれ表示時間と位置を持ち、字幕や他のメモと重なってもかまいません。': 'Simple text, separate from the captions. Each note has its own time and position and may overlap captions or other notes.',
    '>再生位置にメモを追加<': '>Add note at playhead<',
    "'先に動画を読み込んでください。'": "'Load a video first.'", "'数値を入力してください。'": "'Enter a number.'",
    '`出力の形を ${shape.ratio} にしました。`': '`Output shape set to ${shape.ratio}.`',
    '`元の動画 ${media.width} × ${media.height}（${ratioName(media.width, media.height)}）· `': '`Source ${media.width} × ${media.height} (${ratioName(media.width, media.height)}) · `',
    '`${source}出力 ${out.width} × ${out.height} · ': '`${source}Output ${out.width} × ${out.height} · ',
    '`動画の収め方を「${item.name}」にしました。`': '`Fill set to “${item.name}”.`',
    "'動画はすでに出力と同じ形なので、この設定は変化しません。'": "'The video already has the output shape, so this setting changes nothing.'",
    "'余白の色を変えました。'": "'Bar color changed.'",
    '`区間${index + 1}の開始`': '`Section ${index + 1} start`', '`区間${index + 1}の終了`': '`Section ${index + 1} end`',
    "'動画を読み込むとトリムできます。'": "'Load a video to trim it.'",
    '`区間${i + 1}: ${sec(clip.start)}–${sec(clip.end)}`': '`Section ${i + 1}: ${sec(clip.start)}–${sec(clip.end)}`',
    '`書き出し ${sec(kept)}`': '`Exported ${sec(kept)}`', '`${clips.length}区間`': '`${clips.length} sections`', '`${sec(removed)} を削除`': '`${sec(removed)} removed`',
    '`区間${i + 1} 開始`': '`Section ${i + 1} start`', "'終了', clip.end": "'End', clip.end",
    "`区間${index + 1}の${side === 'start' ? '開始' : '終了'}時刻は ${sec(low)}〜${sec(high)} の範囲にしてください。`": "`Section ${index + 1} ${side === 'start' ? 'start' : 'end'} must be between ${sec(low)} and ${sec(high)}.`",
    "'トリムを更新しました。'": "'Trim updated.'",
    '`レイアウトを「${layout.name}」にしました。`': '`Layout set to “${layout.name}”.`', "text: 'カスタム'": "text: 'Custom'",
    '`パネル${i + 1}`': '`Panel ${i + 1}`', "'パネルを追加しました。'": "'Panel added.'", "'＋ パネル'": "'+ Panel'", "'パネルを削除しました。'": "'Panel deleted.'", "'選択したパネルを削除'": "'Delete selected panel'",
    "['source', '切り抜く範囲'], ['target', '出力での位置']": "['source', 'Crop area'], ['target', 'Position in the output']", '`${title}（%）`': '`${title} (%)`',
    "[['x', '左'], ['y', '上'], ['w', '幅'], ['h', '高さ']]": "[['x', 'Left'], ['y', 'Top'], ['w', 'Width'], ['h', 'Height']]",
    "'パネルを更新しました。'": "'Panel updated.'", "'切り抜く範囲を更新しました。'": "'Crop updated.'", "'パネルを移動しました。'": "'Panel moved.'",
    "'不透明度'": "'Opacity'", "'不透明度を変えました。'": "'Opacity changed.'", '`画像${i + 1}`': '`Image ${i + 1}`', "'重ねる順番'": "'Layer'",
    "'字幕の下'": "'Under captions'", "'字幕の上'": "'Over captions'", "'画像を字幕の下にしました。'": "'Image placed under the captions.'", "'画像を字幕の上にしました。'": "'Image placed over the captions.'",
    "'画像を画面いっぱいにしました。'": "'Image fitted to the frame.'", "'画面いっぱいに'": "'Fit to frame'", "'画像を削除しました。'": "'Image deleted.'", "}, '削除'))": "}, 'Delete'))",
    "'位置と大きさ（%）'": "'Position and size (%)'", "'画像の位置を更新しました。'": "'Image position updated.'",
    "'画像を読み込めませんでした。'": "'Could not read the image.'", "'読み込める画像ではありません。'": "'That file is not a readable image.'",
    '`画像は${J.VIDEO_OVERLAY_LIMIT}枚までです。`': '`Use at most ${J.VIDEO_OVERLAY_LIMIT} images.`',
    "'透明部分のある PNG（または WebP）を選んでください。'": "'Choose a PNG (or WebP) image with transparency.'", "'画像が大きすぎます（約6 MBまで）。'": "'The image is too large (limit about 6 MB).'",
    "'画像を追加しました。'": "'Image added.'", "'JIZURA の重ね合わせテンプレートではありません。'": "'That is not a JIZURA overlay template.'", "'テンプレートを読み込みました。'": "'Template loaded.'",
    "'メモの文字を入力してください。'": "'Enter the note text.'",
    '`メモは 0:00.0〜${sec(duration())} の中で、終了を開始より後にしてください。`': '`Keep the note between 0:00.0 and ${sec(duration())}, with its end after its start.`',
    "'メモを更新しました。'": "'Note updated.'", '`メモ${i + 1}`': '`Note ${i + 1}`', "'文字', make('textarea'": "'Text', make('textarea'",
    "'開始（秒）'": "'Start (s)'", "'終了（秒）'": "'End (s)'", "'横位置（%）'": "'Horizontal (%)'", "'縦位置（%）'": "'Vertical (%)'", "'文字の大きさ（%）'": "'Text size (%)'",
    "'色', make('input'": "'Color', make('input'", "'メモを削除しました。'": "'Note deleted.'", "'メモを削除'": "'Delete note'",
    "'再生位置を、残す区間の中（端から少し離れた位置）に置いてください。'": "'Put the playhead inside a kept section, a little away from its edges.'",
    '`${sec(time)} で分割しました。`': '`Split at ${sec(time)}.`', "'最後の区間は削除できません。'": "'The last section cannot be deleted.'", "'区間を削除しました。'": "'Section deleted.'",
    "'再生位置を、削除した部分（縞模様の部分）に置いてください。'": "'Put the playhead on a removed (striped) part.'", "'削除した部分を戻しました。'": "'Removed part restored.'",
    "'動画全体に戻しました。'": "'Full video restored.'", "'先に画像を追加してください。'": "'Add an image first.'", "text: '新しいメモ'": "text: 'New note'", "'メモを追加しました。'": "'Note added.'",
}

EXPORT = {
    "'エンコーダーが出力を返しません'": "'The encoder returned no output'",
    "'（ソフトウェア）'": "' (software)'",
    "'ファイルを仕上げ中'": "'Finishing the file'",
    '`動画のフレームが足りません（${outFrames}/${total}）`': '`Frames are missing (${outFrames}/${total})`',
    "'音声のエンコードに失敗しました: '": "'Audio encoding failed: '",
    "'エンコーダーが応答しません'": "'The encoder stopped responding'",
    "'「大きな動画用（ファイルに直接保存）」か、'": "'use “For large videos (save straight to a file)”, or '",
    '`（${vc.label}・ソフトウェアで再試行 ${k}）`': '` (${vc.label}, retry in software ${k})`',
    "'解像度・fps・画質を下げて試してください。詳細：'": "'try a lower resolution, fps or quality. Details: '",
    "'MP4 を書き出せませんでした。'": "'Could not export the MP4: '",
    "'エンコーダーが停止しました'": "'The encoder stopped'",
    "'音声のエンコードが途中で止まりました（' + aChunks + '）。もう一度書き出してください'": "'Audio encoding stopped partway (' + aChunks + '). Please export again'",
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome か Edge の最新版で開いてください。': 'Video encoding (WebCodecs) is unavailable. Open in the latest Chrome or Edge.',
    'キャンセルしました': 'Canceled', 'フレーム ': 'Frame ',
    '音声をエンコード中': 'Encoding audio', '完了': 'Done',
}

AE_UI = {
    "'文字PV系の部品を使う'": "'Use typographic parts'", "'キネティックの部品を使う'": "'Use kinetic parts'", "'ホラーの演出も使う'": "'Include horror effects'",
    "'線・数字・字組みだけで見せる、文字PVらしい部品（約50）'": "'About 50 parts that work with lines, numbers and type alone'",
    "'語ごとに動く・跳ねる・積み上がる、動き重視の部品（約50）'": "'About 50 motion-first parts: words move, bounce and stack one by one'",
    "'不気味な雰囲気の部品（約50）と配色セット3。オンにすると、おまかせの雰囲気に「ホラー」が加わります（ホラーの部品は雰囲気が「ホラー」のときだけ使います）'": "'About 50 eerie parts and 3 styles. When on, Randomize adds a Horror mood (horror parts are used only in that mood)'",
    "'  〔ホ〕'": "'  [H]'",
    "'\u3000縦長のとき'": "'  On tall frames'",
    "'上下に分ける'": "'Top / bottom'",
    "'左右に分ける'": "'Left / right'",
    "'軽量（AE での再生を軽く）'": "'Lightweight (faster playback in AE)'",
    "'色ズレの複製・紙の質感・グロー・粒子・一部の画面効果を省いて、After Effects での再生を軽くします（長い曲におすすめ）'": "'Leaves out the colour-shift copies, paper texture, bloom, grain and some screen effects so the composition plays back faster in After Effects (recommended for long songs)'",
    "'中央を空ける（キャラクター用：横長は左右・縦長は上下に配置）'": "'Keep the centre free (for a character: left / right on wide, top / bottom on tall frames)'",
    "'中央にキャラクターなどを重ねる前提で、文字と演出をカットごとの帯（横長の画面は左右、縦長は上下。行ごとに交互）に置きます。背景と画面効果は画面全体のままです'": "'For a character or other footage in the middle: each cut is laid out in a side band (left / right on wide frames, top / bottom on tall ones, alternating line by line). Backgrounds and screen effects still cover the whole frame.'",
    "'中止'": "'Stop'",
    "'作成を止めます（そこまでのカットでコンポを仕上げます）'": "'Stop building (the composition is finished with the cuts built so far)'",
    "'JIZURA：いま作成中です。終わるまで待つか「中止」を押してください'": "'JIZURA: a build is running. Wait for it to finish or press Stop.'",
    "' カット' : '効果を追加中'": "' cuts' : 'adding effects'",
    "'中止しています…（作成済みのカットで仕上げます）'": "'Stopping… (finishing with the cuts built so far)'",
    "'中止（' + job.done + ' / ' + job.total + ' カット）'": "'Stopped (' + job.done + ' / ' + job.total + ' cuts)'",
    '歌詞の言語': 'Lyrics language', "['自動判定', '日本語',": "['Auto-detect', '日本語',",
    '中国語（繁体字・簡体字）や韓国語の歌詞は、その文字を持つ書体で組みます（各スタイルの書体の雰囲気に近いものに置き換え）。自動判定はかな・ハングル・繁体字／簡体字に特有の字から判断します': 'Chinese (Traditional / Simplified) and Korean lyrics are set in fonts that have those characters, close in feel to each style. Auto-detect looks at kana, Hangul and the characters that differ between Traditional and Simplified Chinese.',
    "var JZ_SAMPLE = '夜明けの色を/覚えてる\\nほどけた声が遠くで鳴った\\nねえ、まだ間に合うかな\\n*透明*なままじゃ終われない!';": "var JZ_SAMPLE = 'I remember/the color of dawn\\nA voice faded into the distance\\nCan we still make it in time?\\n*Transparent* is not how this ends!';",
    'JIZURA 字面  lyric motion': 'JIZURA  lyric motion',
    '（': ' (', '）': ')', '部品': 'techniques',
    '歌詞（1行=1フレーズ　/ 区切り　*強調*　行末! インパクト）': 'One phrase per line. / = cut, *word* = emphasis, final ! = impact',
    'おまかせで生成（押すたびに別の演出）': 'Create a variation',
    'スタイル・雰囲気・演出の強さ・配色・シードをまるごとランダムに決めて、新しいコンポを作ります': 'Randomize style, mood, effects, colors and seed, then create a composition.',
    'オフのときは最初の公開版の演出（356部品・スタイル12種）だけを使います。オンにすると、あとから追加した演出・スタイル・書体も候補になります': 'Include techniques, styles and fonts added after the first release in random picks.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィックと、和風のスタイル。オフにすると自動では選ばれません（追加分の判定のあとに適用）': 'Include Japanese motifs such as lanterns, shoji, fans and cherry blossoms in automatic picks.',
    'アクティブなコンポと同じ': 'Same as active comp',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'グリーンバック／ブラックバック：白い文字と演出だけを単色の背景の上に作ります（背景の模様・紙・粒子・周辺減光なし）。グリーンはキーイング、ブラックはスクリーン合成で抜けます': 'Solid green or black background behind white text and effects. Key out green or use Screen blending for black.',
    '自動（文字数・BPM から） / LRCの時刻': 'Auto (text length and BPM) / LRC timestamps',
    '選択レイヤーのマーカーを行頭に使う': 'Use selected layer markers for line starts',
    'コンポマーカーを行頭に使う': 'Use composition markers for line starts',
    '選択中の音声レイヤーを新しいコンポに入れる': 'Include selected audio layer in new composition',
    '標準（すべての手法を使う）': 'Standard (all techniques)',
    '雰囲気ごとに使うレイアウト・登場・退場の手法が絞られます（シードで再現）': 'Mood influences the selection of layouts, entrances and exits (reproducible by seed).',
    '背景に合うアクセント色とズレ色A/Bをランダムに選びます（明るさは背景に合わせて自動調整）': 'Randomize accent and offset colors with automatic brightness adjustment.',
    '配色を変更しました — 「コンポを生成する」で反映されます': 'Palette changed. Create a composition to apply it.',
    'ブラウザ版 JIZURA の「AE用に書き出し」で作った .json を読み込み、': 'Import a JSON file made with Export for AE in the browser app.',
    '同じタイミング・レイアウト・演出で編集可能なコンポを組みます。': 'Create an editable composition with the same timing, layouts and effects.',
    '思ったとおりにできないときは、下のボタンで診断レポート（JIZURA_report.txt）を保存して送ってください。': 'If the result looks wrong, save a diagnostic report (JIZURA_report.txt).',
    '診断レポートを保存（最後に作ったコンポ）': 'Save diagnostics for last composition',
    'PostScript名で指定（見つからない指定はここに落ちます）': 'Specify PostScript font names (fallbacks when a font is unavailable).',
    '常にこの4書体を使う（自動選択しない）': 'Always use these four fonts (disable automatic selection)',
    '選択中のテキストレイヤーの書体を「見出し」に': 'Use selected text layer font for display text',
    'Noto Sans JP / Noto Serif JP / Dela Gothic One などが入っていれば自動で使います（AE 2024以降）。': 'Installed Google Fonts are used automatically in After Effects 2024 or later.',
    'この PC に無い書体: ': 'Fonts missing on this computer: ',
    'JIZURA：次の書体がこの PC に無いため、近い書体で作りました。': 'JIZURA: These fonts are unavailable, so similar fonts were used.',
    'どれも Google Fonts（fonts.google.com）から無料で入れられます。入れて After Effects を再起動し、作り直すと、ブラウザ版と同じ書体になります。': 'Install them from Google Fonts, restart After Effects and rebuild for the closest browser match.',
    'JIZURA：この After Effects では書体が入っているかを確認できないため（AE 2024 より前）、「フォント」タブで指定した書体で作りました。': 'JIZURA: This version of After Effects cannot check installed fonts, so the font tab fallbacks were used.',
    'ブラウザ版と同じ書体にするには、使われている書体（Google Fonts）を入れて「フォント」タブで指定するか、AE 2024 以降で作ってください。': 'For matching type, install the Google Fonts used in the browser and select them in the font tab, or use AE 2024 or later.',
    'JIZURA：生成しましたが、一部に注意があります：': 'JIZURA: Composition created with some warnings:',
    'マーカーを使うには、コンポを開いてください': 'Open a composition to use markers',
    'マーカーのあるレイヤーを選択してください': 'Select a layer with markers',
    'マーカーが見つかりません': 'No markers found', 'マーカーを読めませんでした: ': 'Could not read markers: ',
    '構成の計算でエラー: ': 'Could not plan composition: ',
    '配色の値が読めないため、スタイルの色のままにしました（#RRGGBB 形式で入力）': 'Invalid color. Style colors were kept (enter #RRGGBB).',
    'JSONを読めませんでした: ': 'Could not read JSON: ',
    'JIZURA の AE用JSON ではないようです': 'This is not a JIZURA AE project JSON',
    'このパネルに無い表現 ': 'Techniques unavailable in this panel: ',
    'JIZURA：この JSON には、このパネルが作れない表現が ': 'JIZURA: This JSON contains ',
    ' 箇所あり、近い表現に置き換えました。': ' unsupported techniques; similar ones were substituted.',
    ' 箇所を、近い表現で作りました': ' instances were replaced by similar techniques',
    'ブラウザ版より古いパネルを使っている可能性があります。最新の JIZURA_AE.jsx（v': 'This panel may be older than the browser edition. Install the latest JIZURA_AE_en.jsx (v',
    '・860 部品）に差し替えて、After Effects を再起動してください。': ', 860 techniques) and restart After Effects.',
    '先にコンポを作ってください（このパネルで最後に作ったコンポを調べます）': 'Create a composition first; diagnostics inspect the last one created here.',
    '最後に作ったコンポが見つかりません（削除された可能性があります）': 'The last composition could not be found (it may have been deleted).',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this can take a few seconds)',
    'レポートを保存しました：': 'Report saved: ',
    'レポートを保存できませんでした（環境設定 → スクリプトとエクスプレッション →「スクリプトによるファイルへの書き込みとネットワークへのアクセスを許可」をオンにしてください）。': 'Could not save report. Allow scripts to write files and access the network in After Effects preferences.',
    'テキストレイヤーを選択してください': 'Select a text layer', 'テキストレイヤーではありません': 'This is not a text layer',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    '選択中の音声レイヤーも入れる': 'Include selected audio layer',
    'JSONを選んで生成…': 'Open JSON and build…',
    'スタイルの色を上書き': 'Override style colors', 'ランダム配色': 'Random palette',
    'コンポを生成する': 'Create composition', 'JSONから': 'From JSON', '歌詞から': 'From lyrics',
    'おまかせ：': 'Variation: ', 'ランダム配色': 'Random palette',
    '生成中…': 'Building…', '生成中にエラー: ': 'Build error: ',
    '診断：エクスプレッションのエラー ': 'Diagnostics: expression errors ',
    'JIZURA 診断：エクスプレッション ': 'JIZURA diagnostics: expressions ',
    ' 個のうち、エラー ': ', errors ', ' 個': '',
    '（時間の上限で途中まで）': ' (partial, time limit)', '（途中まで）': ' (partial)',
    '置換あり': 'Substitutions', '注意 ': 'Warnings: ', '件': '',
    '書体の代用 ': 'Font substitutions: ', '箇所': ' instances',
    '歌詞が空です': 'Lyrics are empty', '準備OK': 'Ready',
    '曲名': 'Song title', 'アーティスト': 'Artist', 'スタイル': 'Style',
    'サイズ': 'Size', '背景': 'Background', 'タイミング': 'Timing',
    '行の長さ': 'Line duration', '演出': 'Effects', '雰囲気': 'Mood',
    '動きの強さ': 'Motion strength', 'グリッチ': 'Glitch', '色ズレ': 'Color offset',
    '装飾の量': 'Decoration amount', 'カットの細かさ': 'Cut density',
    '質感': 'Texture', '背景の切替': 'Background changes',
    '2コマ打ち': 'On twos', 'フラッシュ': 'Flash',
    'スタイル次第': 'Auto by style', '非表示': 'Hide', '表示': 'Show',
    'シード': 'Seed', 'シャッフル': 'Shuffle',
    'アクセント・ズレ色': 'Accent and offset colors', 'アクセント': 'Accent',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B',
    'フォント': 'Fonts', '見出し': 'Display', '明朝': 'Serif',
    '小さな文字': 'Small text', '等幅': 'Monospace', '・': ' · ',
    '追加': 'New', '和': 'JP',
}

CEP = {
    '<label class="row ae-light-row" title="色ズレの複製・紙の質感・グロー・粒子・一部の画面効果を省いて、After Effects での再生を軽くします（長い曲におすすめ）"><input type="checkbox" class="ae-light"><span>軽量（AE での再生を軽く）</span></label>': '<label class="row ae-light-row" title="Leaves out the colour-shift copies, paper texture, bloom, grain and some screen effects so the composition plays back faster in After Effects (recommended for long songs)"><input type="checkbox" class="ae-light"><span>Lightweight (faster playback in AE)</span></label>',
    '選んだ範囲にカットがありません': 'No cuts in the selected range',
    "`${R.from + 1}${R.to > R.from ? '–' + (R.to + 1) : ''}行目・`": "`lines ${R.from + 1}${R.to > R.from ? '–' + (R.to + 1) : ''} · `",
    "'効果を追加中'": "'adding effects'",
    '`・残り約 ${Math.max(1, Math.round(left))} 秒`': '` · about ${Math.max(1, Math.round(left))} s left`',
    '`中止しました：「${r.name}」は ${r.cuts} / ${r.total} カットまでです`': '`Stopped: “${r.name}” has ${r.cuts} of ${r.total} cuts`',
    "'作成を中止しました'": "'Build stopped'",
    "'中止しています…（作成済みのカットで仕上げます）'": "'Stopping… (finishing with the cuts built so far)'",
    "'中止'": "'Stop'",
    "'作成を止めます（そこまでのカットでコンポを仕上げます）'": "'Stop building (the composition is finished with the cuts built so far)'",
    '「${r.name}」を作成しました': 'Created “${r.name}”',
    'AE の「${r.name}」で拍を合わせました': 'Synced beats to “${r.name}” in AE',
    '曲（<span class="ae-audio-name"></span>）をコンポに入れる': 'Include audio (<span class="ae-audio-name"></span>) in composition',
    ' に接続しました': ' connected',
    'After Effects に接続中…（初回は数秒かかります）': 'Connecting to After Effects…',
    'After Effects に接続しました': 'connected to After Effects',
    'After Effects に接続できませんでした: ': 'Could not connect to After Effects: ',
    'After Effects に接続できませんでした': 'Could not connect to After Effects',
    'この PC に無い書体（': 'Fonts missing on this computer (',
    '）は近い書体で作りました。Google Fonts から入れて AE を再起動すると、同じ書体になります': ') were replaced with similar fonts. Install them from Google Fonts and restart AE for a closer match.',
    'この AE（2024 より前）では書体の有無を確認できないため、スクリプト版パネルの「フォント」タブの書体（未設定なら游ゴシック・游明朝）で作りました': 'AE before 2024 cannot detect installed fonts; ScriptUI font settings or system fallbacks were used.',
    'レポートを保存できませんでした（AE の環境設定「スクリプトによるファイルへの書き込み…を許可」をオンに）': 'Could not save report. Enable script file writing in AE preferences.',
    'このパネルでは曲ファイルを直接読めません。「曲を読み込む」から選んでください': 'This panel cannot read audio directly. Use Import audio instead.',
    'この曲ファイルは読み込めませんでした（wav / mp3 / m4a などを使ってください）': 'Could not read this audio file. Try WAV, MP3 or M4A.',
    '最後に作ったコンポを調べて JIZURA_report.txt を保存します（うまく作れないときに送ってください）': 'Check the last composition and save a JIZURA_report.txt diagnostic file.',
    'AE で選択している曲のレイヤーを読み込み、拍に合わせます（コンポを作るときにその曲も入ります）': 'Import the selected AE audio layer, analyze beats and include it in the composition.',
    '選択レイヤー（無ければコンポ）のマーカーを、各行の開始時刻にします': 'Use selected layer markers (or composition markers) for line start times.',
    '今の構成で After Effects にコンポを作ります': 'Build an After Effects composition from this arrangement.',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this may take a few seconds)',
    'コンポを作成中…': 'Building composition…',
    'AEで選択中の曲': 'Selected AE audio',
    'AEのマーカーを行頭に': 'Use AE markers for lines',
    'AEでコンポを生成': 'Build in AE',
    'After Effects にコンポを作る': 'Build composition in After Effects',
    'After Effects にコンポを作成しました': 'Composition created in After Effects',
    '診断レポートを保存': 'Save diagnostic report',
    'コンポに入れる': 'include in composition',
    '作成できませんでした: ': 'Could not create composition: ',
    '作成できませんでした': 'Could not create composition',
    '近い表現で置換 ': 'Substitutions: ', '注意 ': 'Warnings: ',
    '診断：エクスプレッション ': 'Diagnostics: expressions ',
    ' 個のうちエラー ': ', errors ', ' 個': '', '（途中まで）': ' (partial)',
    '曲ファイルを読めませんでした: ': 'Could not read audio: ',
    'この曲ファイルは読み込めませんでした': 'Could not read this audio file',
    'のマーカー ': ' markers: ', ' 個を行の開始時刻にしました': ' line start times set',
    'レイヤー': 'Layer', 'コンポ': 'Composition',
    '（残り ': ' (remaining ', ' 行は自動）': ' lines automatic)',
    '動画・画像': 'Video and images',
    '保存しました: ': 'Saved: ', '保存': 'Save',
    ' カット': ' cuts', ' 秒': ' s', '曲入り': 'with audio',
    ' 箇所': ' instances', ' 件': ' items', 'レポート: ': 'Report: ',
    '「': '“', '」': '”', '（': ' (', '）': ')', '・': ' · ',
}

CEP_HOST = {
    "'生成中のコンポがありません'": "'No composition is being built'",
    'JIZURA の構成データではありません': 'This is not JIZURA project data',
    'コンポを開いて、曲のレイヤーを選択してください': 'Open a composition and select an audio layer',
    '曲（音声ファイル）のレイヤーを選択してください': 'Select an audio file layer',
    'コンポを開いてください': 'Open a composition',
    'マーカーが見つかりません（曲のレイヤーかコンポにマーカーを打ってください）': 'No markers found. Add markers to the audio layer or composition.',
    '構成データの一時ファイルが見つかりません': 'Temporary project data file not found',
    '先にこのパネルでコンポを作ってください': 'Create a composition in this panel first',
}


def localize_cep(source, host=False):
    return replace_copy(source, CEP_HOST if host else CEP)


def localize_ae(source):
    return (replace_copy(source, AE_UI)
            .replace('lyr.preferredSize = [340, 150]', 'lyr.preferredSize = [440, 150]')
            .replace('preferredSize.width = 86', 'preferredSize.width = 120')
            .replace('preferredSize.width = 70', 'preferredSize.width = 95'))


# Strings that were still falling through to Japanese (full-phrase keys so shorter label rules cannot half-translate them).
BODY.update({
    '字幕の文字<input id="captionEditText"': 'Caption text<input id="captionEditText"',
    'title="この字幕をループ再生し、各単語が始まる瞬間に Space を押して単語のタイミングを合わせます">単語を同期': 'title="Loop this caption and press Space as each word starts to set the word timing">Sync words',
    '<dt>タイミングの精度</dt>': '<dt>Timing source</dt>',
    'title="タップ同期: 選んだ字幕から最後まで（またはルーラーで指定した範囲）を、動画を再生しながら Space で合わせます">同期': 'title="Tap sync: play the video and press Space as each caption starts, from the selected caption to the end (or inside the range marked on the ruler)">Sync',
    'aria-label="時間目盛り（クリックまたはドラッグで移動）"': 'aria-label="Time ruler (click or drag to move)"',
})
CAPTION_UI.update({
    "'ループする字幕を選ぶか、ルーラーを Alt+ドラッグして範囲を指定してください。'": "'Select a caption to loop, or Alt+drag on the ruler to mark a range.'",
    '`ループ ${fmt(region.start)}–${fmt(region.end)}`': '`Loop ${fmt(region.start)}–${fmt(region.end)}`',
    '`次: 「${label(next)}」（${done + 1} / ${total}）`': '`Next: “${label(next)}” (${done + 1} / ${total})`',
    '`すべてタップしました（${total}件）。「確定」で反映します。`': '`All ${total} tapped. Press Confirm to apply.`',
    "'単語を押すと強調を変えられます。'": "'Press a word to change its highlight.'",
    "'台本のテキストを貼り付けてください。'": "'Paste the script text first.'",
    '`台本は ${J.captionTimeline.SCRIPT_MAX_LINES} 行までです。`': '`A script can have at most ${J.captionTimeline.SCRIPT_MAX_LINES} lines.`',
    "'ここには台本を入れる空きがありません。再生位置を動かすか、ルーラーで範囲を指定してください（1行あたり 0.1 秒以上必要です）。'": "'There is no room for a script here. Move the playhead or mark a range on the ruler (each line needs at least 0.1 s).'",
    '`${count} 行 → ${count} 件の字幕`': "`${count} ${count === 1 ? 'line' : 'lines'} → ${count} ${count === 1 ? 'caption' : 'captions'}`",
    '`${commands.length} 件の字幕を追加しました。「同期」で話すタイミングに合わせます。`': "`Added ${commands.length} ${commands.length === 1 ? 'caption' : 'captions'}. Use Sync to match the speech timing.`",
    "{ text: '全体に合わせる'": "{ text: 'Match project'",
    "ui.exportAbort ? 'キャンセル' : '書き出しを開始'": "ui.exportAbort ? 'Cancel' : 'Start export'",
    "exportState('書き出しを準備しています…', 0)": "exportState('Preparing the export…', 0)",
    "const done = `書き出しました（${result.frameCount}フレーム・音声${result.audio.mode !== 'none' ? '保持' : 'なし'}・${result.metrics.elapsedSeconds.toFixed(1)}秒）。`": "const done = `Export complete (${result.frameCount} frames · audio ${result.audio.mode !== 'none' ? 'preserved' : 'none'} · ${result.metrics.elapsedSeconds.toFixed(1)} s).`",
    "showState('自動保存 ' + clock(record.savedAt))": "showState('Autosaved ' + clock(record.savedAt))",
    "showState('自動保存できません', true)": "showState('Autosave unavailable', true)",
    "['Every', '言葉', 'ひとつ', '100%']": "['Every', 'word', 'counts', '100%']",
})


def replace_copy(source, glossary):
    # Longest first protects complete phrases from shorter label replacements.
    for japanese, english in sorted(glossary.items(), key=lambda pair: -len(pair[0])):
        source = source.replace(japanese, english)
    return source


def localize_body(source):
    return replace_copy(source, BODY).replace('You own the<strong>', 'You own the <strong>')


def localize_js(source, filename):
    if filename.endswith('12_ui.js'):
        return replace_copy(source, UI)
    if filename.endswith('12c_caption_workbench.js') or filename.endswith('12d_caption_autosave.js') or re.search(r'12b[o-z]_caption_', filename):
        return replace_copy(source, CAPTION_UI)
    if filename.endswith('12a_video_edit_ui.js'):
        return replace_copy(source, VIDEO_UI)
    if filename.endswith('11_export.js'):
        return replace_copy(source, EXPORT)
    return source
